#!/usr/bin/env python3
"""Event-timed check of the reserve recursion in a finite pool (Section 6.5 of the paper).

The annual recursion of Section 6 receives a year's interest before paying that year's losses,
keeps exposure constant and uses the conditional (infinitely granular) loss rate. This script runs
the pool at the contract's own timing: N slots of equal principal lent in back-to-back 30-day
loans; at the end of each term a loan either repays principal plus simple interest, of which the
share r goes to the reserve and the rest to lenders, or defaults; a defaulted loan is written off
one late period (30 days) later, when the reserve pays its principal first and lenders bear the
rest, and only then is the slot re-lent. The systematic factor is fixed for each 365-day year and
the number of defaults among the active slots in a term is binomial with the conditional per-loan
probability. Deposits are constant at N/u, so exposure is replenished as in the recursion; what
the check adds is the timing of interest against losses, the write-off delay and the finite size.

Usage: python3 scripts/event_timed.py <path to microcredit-contract>     (about a minute)

Writes data/event_timed_years.csv, data/table_event_timed.tex, data/table_event_quantile.tex and
data/event_summary.tex (macros used by paper.tex). Every draw uses a fixed seed.
"""
import csv
import pathlib
import sys

import numpy as np

CONTRACT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../../microcredit-contract")
sys.path.insert(0, str(CONTRACT / "analysis/credit_risk"))
import vasicek as vs  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/event_timed.py; do not edit.\n"
SEED = 20261005
PATHS = 200_000
YEARS = 30
U = 0.85
FEE = 0.0
PD = 0.05
PREMIUM = 0.08                       # the production premium at PD 5%
APR = vs.EFFR + PREMIUM
DAYS = vs.DAYS_PER_YEAR
TERMS_PER_YEAR = 12                  # terms of 365/12 = 30.4 days, so that every year holds twelve
TERM = DAYS / TERMS_PER_YEAR         # (the contract's default is 30 days, 12.17 a year; a calendar
N_TERMS = YEARS * TERMS_PER_YEAR     # year then holds 12 or 13 term ends, which would make the
RHO = vs.basel_other_retail_correlation(PD)   # year-by-year comparison with the recursion noisy)
EL = float(vs.replenished_expected_loss(PD, RHO, term_days=TERM))
R_EL = EL / APR
R_REC = 0.65                         # the production share at commit b725a85
I_TERM = APR * TERM / DAYS           # simple interest per term per unit of principal
SIZES = (100, 500, 5000)
# The write-off lag is one term: the contract's late period is 30 days after the due date.


def simulate(n_slots, r, tag):
    """Per year and path: lenders' return per unit of deposits, lenders' loss, reserve payments
    and write-offs (per unit of principal, i.e. in slots)."""
    rng = np.random.default_rng(np.random.SeedSequence([SEED, tag]))
    reserve = np.zeros(PATHS)
    late = np.zeros(PATHS, dtype=np.int64)
    deposits = n_slots / U
    year_int = np.zeros((YEARS, PATHS))
    year_loss = np.zeros((YEARS, PATHS))
    year_paid = np.zeros((YEARS, PATHS))
    year_wo = np.zeros((YEARS, PATHS))
    cur_year = -1
    p_loan = None
    for k in range(N_TERMS):
        y = k // TERMS_PER_YEAR                            # the year in which this term ends
        if y != cur_year:
            cur_year = y
            p_year = np.clip(vs.conditional_pd(PD, RHO, rng.standard_normal(PATHS)), 1e-12, 1 - 1e-12)
            p_loan = np.asarray(vs.loan_pd_from_annual_pd(p_year, term_days=TERM))
        # Write off last term's defaults before this term's interest arrives: the reserve pays
        # first, lenders bear the rest.
        loss = late.astype(float)
        paid = np.minimum(reserve, loss)
        reserve -= paid
        year_loss[y] += loss - paid
        year_paid[y] += paid
        year_wo[y] += loss
        # This term's loans: the active slots repay with interest or default.
        active = n_slots - late
        d = rng.binomial(active, p_loan)
        interest = (active - d) * I_TERM
        reserve += r * interest
        year_int[y] += (1 - FEE - r) * interest
        late = d
    ret = (year_int - year_loss) / deposits
    return ret, year_loss / deposits, year_paid, year_wo


def annual_rows():
    """The annual recursion's results (locked policy, PD 5%) from data/reserve_years.csv."""
    out = {}
    for row in csv.DictReader(open(OUT / "reserve_years.csv")):
        if row["annual_pd"] == "0.05" and row["policy"] == "locked":
            out.setdefault(row["reserve_share_case"], {})[int(row["year"])] = row
    return out


def main():
    OUT.mkdir(exist_ok=True)
    macros = {}
    annual = annual_rows()
    cases = []
    year_rows = []
    tag = 0
    for r_label, r in (("expected loss", R_EL), ("recommended", R_REC)):
        for n in SIZES:
            tag += 1
            ret, ll, paid, wo = simulate(n, r, tag)
            cover1 = float(paid[0].sum() / wo[0].sum())
            p_loss = (ll > 1e-12).mean(axis=1)
            mean_ret = ret.mean(axis=1)
            # Gross annual loss rate per unit of exposure, years 2 to 30 (year 1 lacks the
            # write-offs of a preceding year's last term).
            gross = (wo[1:] / n).ravel()
            cases.append({"case": r_label, "r": r, "n": n, "mean_ret": mean_ret, "p_loss": p_loss, "cover1": cover1,
                          "q999": float(np.quantile(gross, 0.999)), "q99": float(np.quantile(gross, 0.99)),
                          "mean_loss": float(gross.mean())})
            for t in range(YEARS):
                year_rows.append({"reserve_share_case": r_label, "reserve_share": round(r, 6), "n_loans": n, "year": t + 1,
                                  "mean_return": float(mean_ret[t]), "p_lender_loss": float(p_loss[t]),
                                  "reserve_coverage_of_losses": float(paid[t].sum() / max(wo[t].sum(), 1e-12))})
    with open(OUT / "event_timed_years.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(year_rows[0]))
        w.writeheader()
        w.writerows(year_rows)

    def pct(x, d=2):
        return f"{100 * float(x):.{d}f}"

    # Table: lenders' return and loss probability by year, event-timed against the annual recursion.
    lines = []
    for r_label in ("expected loss", "recommended"):
        a = annual[r_label]
        share = pct(a[1]["reserve_share"], 0)
        cells = " & ".join(f"{pct(a[y]['mean_apy'])}\\% & {pct(a[y]['p_lender_loss'], 1)}\\%" for y in (1, 5, 10, 30))
        lines.append(f"{share}\\%, annual recursion & $\\infty$ & {cells} & -- \\\\")
        for c in [c for c in cases if c["case"] == r_label]:
            cells = " & ".join(f"{pct(c['mean_ret'][y - 1])}\\% & {pct(c['p_loss'][y - 1], 1)}\\%" for y in (1, 5, 10, 30))
            lines.append(f"{share}\\%, event-timed & {c['n']:,} & {cells} & {pct(c['cover1'], 0)}\\%".replace(",", "{,}") + " \\\\")
    with open(OUT / "table_event_timed.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")

    # Table: the 99.9% annual loss quantile, event-timed, against the approximations.
    q_static = float(vs.loss_quantile(PD, RHO, 0.999))
    q_rep = float(vs.replenished_loss_quantile(PD, RHO, 0.999, term_days=TERM))
    lines = []
    for n in SIZES:
        c = next(c for c in cases if c["case"] == "recommended" and c["n"] == n)
        ga = float(vs.granularity_adjustment(PD, RHO, 0.999, n))
        combined = q_rep + ga
        err = combined / c["q999"] - 1
        lines.append(f"{n:,} & {pct(c['mean_loss'])}\\% & {pct(c['q999'])}\\% & {pct(q_rep + ga)}\\% & {100 * err:+.1f}\\%".replace(",", "{,}") + " \\\\")
        key = {100: "Hundred", 500: "FiveHundred", 5000: "FiveThousand"}[n]
        macros[f"EventQ{key}"] = pct(c["q999"])
        macros[f"CombinedQ{key}"] = pct(combined)
        macros[f"CombinedErr{key}"] = f"{100 * err:+.1f}"
        macros[f"EventMeanLoss{key}"] = pct(c["mean_loss"])
    with open(OUT / "table_event_quantile.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")
    macros["StaticQ"] = pct(q_static)
    macros["ReplenishedQ"] = pct(q_rep)
    macros["ReplenishedEL"] = pct(EL)

    rec500 = next(c for c in cases if c["case"] == "recommended" and c["n"] == 500)
    el500 = next(c for c in cases if c["case"] == "expected loss" and c["n"] == 500)
    rec100 = next(c for c in cases if c["case"] == "recommended" and c["n"] == 100)
    a_rec, a_el = annual["recommended"], annual["expected loss"]
    macros["EventCoverRec"] = pct(rec500["cover1"], 0)
    macros["EventCoverEl"] = pct(el500["cover1"], 0)
    macros["EventYearOneLossRec"] = pct(rec500["p_loss"][0], 1)
    macros["EventYearOneLossRecHundred"] = pct(rec100["p_loss"][0], 1)
    macros["AnnualYearOneLossRec"] = pct(a_rec[1]["p_lender_loss"], 1)
    macros["EventYearOneRetRec"] = pct(rec500["mean_ret"][0])
    macros["AnnualYearOneRetRec"] = pct(a_rec[1]["mean_apy"])
    macros["EventYearTenLossRec"] = pct(rec500["p_loss"][9], 1)
    macros["AnnualYearTenLossRec"] = pct(a_rec[10]["p_lender_loss"], 1)
    macros["EventYearThirtyRetRec"] = pct(rec500["mean_ret"][29])
    macros["AnnualYearThirtyRetRec"] = pct(a_rec[30]["mean_apy"])
    macros["EventYearOneLossEl"] = pct(el500["p_loss"][0], 1)
    macros["AnnualYearOneLossEl"] = pct(a_el[1]["p_lender_loss"], 1)
    macros["EventYearTenLossEl"] = pct(el500["p_loss"][9], 1)
    macros["AnnualYearTenLossEl"] = pct(a_el[10]["p_lender_loss"], 1)
    macros["EventYearThirtyRetEl"] = pct(el500["mean_ret"][29])
    macros["AnnualYearThirtyRetEl"] = pct(a_el[30]["mean_apy"])
    macros["EventPaths"] = f"{PATHS:,}".replace(",", "{,}")
    # Largest absolute difference in mean return between the event-timed pool and the annual
    # recursion over years 5 to 30, per case and size, in percentage points; then the largest over
    # the pools of 500 loans or more and over the pools of 100 loans, both shares.
    diffs = {}
    for c in cases:
        a = annual[c["case"]]
        d = max(abs(c["mean_ret"][y - 1] - float(a[y]["mean_apy"])) for y in range(5, YEARS + 1))
        diffs[(c["case"], c["n"])] = d
        key = {100: "Hundred", 500: "FiveHundred", 5000: "FiveThousand"}[c["n"]]
        macros[f"EventDiffMax{'Rec' if c['case'] == 'recommended' else 'El'}{key}"] = pct(d)
    macros["EventDiffMaxFiveHundredPlus"] = pct(max(d for (case, n), d in diffs.items() if n >= 500))
    macros["EventDiffMaxHundred"] = pct(max(d for (case, n), d in diffs.items() if n == 100))
    macros["EventDiffMaxRecAll"] = pct(max(d for (case, n), d in diffs.items() if case == "recommended"))
    with open(OUT / "event_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(macros)


if __name__ == "__main__":
    main()
