#!/usr/bin/env python3
"""Tables and curves for the paper from the contract repository's credit-risk calibration.

Reads analysis/credit_risk/results/*.csv (written by analysis/credit_risk/run.py at commit b725a85)
and this paper's own data/reserve_*.csv (written by scripts/locked_reserve.py), and evaluates the
closed forms of analysis/credit_risk/vasicek.py on fine grids for the figures.

Usage: python3 scripts/extract_credit_risk.py <path to microcredit-contract>
"""
import csv
import pathlib
import sys

import numpy as np

CONTRACT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../../microcredit-contract")
sys.path.insert(0, str(CONTRACT / "analysis/credit_risk"))
import vasicek as vs  # noqa: E402

RES = CONTRACT / "analysis/credit_risk/results"
OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/extract_credit_risk.py; do not edit.\n"


def rows(name, base=RES):
    return list(csv.DictReader(open(base / name)))


def pct(x, d=1):
    return f"{100 * float(x):.{d}f}"


def bps(x):
    return f"{float(x):,.0f}".replace(",", "{,}")


def write_tex(name, lines):
    with open(OUT / name, "w") as fh:
        fh.write(HEADER)
        for line in lines:
            fh.write(line + " \\\\\n")


def write_csv(name, header, data):
    with open(OUT / name, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        w.writerows(data)


def main() -> None:
    OUT.mkdir(exist_ok=True)

    # Table: default horizons
    lines = []
    for r in rows("pd_annual_to_loan.csv"):
        lines.append(f"{pct(r['annual_pd'], 0)}\\% & {pct(r['loan_pd_30d'], 3)}\\% & {pct(r['hazard_per_year'], 2)}\\% & "
                     f"{pct(r['replenished_defaults_per_exposure_year_30d'], 2)}\\%")
    write_tex("table_horizon.tex", lines)
    lines = []
    for r in rows("pd_loan_to_annual.csv"):
        if float(r["loan_pd_30d"]) in (0.0025, 0.005, 0.01, 0.02, 0.03, 0.05):
            lines.append(f"{pct(r['loan_pd_30d'], 2)}\\% & {pct(r['annual_pd'], 1)}\\% & {pct(r['defaults_per_exposure_year_replenished'], 1)}\\%")
    write_tex("table_loan_to_annual.tex", lines)

    # Table: loss distribution at the Basel correlation
    lines = []
    for r in rows("vasicek_losses.csv"):
        if r["rho_case"] == "Basel":
            lines.append(f"{pct(r['annual_pd'], 0)}\\% & {float(r['rho']):.4f} & {pct(r['el'])}\\% & {pct(r['sd'])}\\% & "
                         f"{pct(r['q0.99'])}\\% & {pct(r['q0.999'])}\\% & {pct(r['es0.999'])}\\% & "
                         f"{pct(r['el_replenished'], 2)}\\% & {pct(r['q0.999_replenished'])}\\%")
    write_tex("table_losses.tex", lines)

    # Table: 99.9% quantile on the correlation grid
    grid = {}
    for r in rows("vasicek_losses.csv"):
        grid.setdefault(r["annual_pd"], {})[r["rho_case"]] = r["q0.999"]
    cases = ["Basel", "0.02", "0.05", "0.1", "0.15", "0.2", "0.3"]
    lines = []
    for pd_, g in grid.items():
        lines.append(f"{pct(pd_, 0)}\\% & " + " & ".join(pct(g[c]) + "\\%" for c in cases if c in g))
    write_tex("table_rho_grid.tex", lines)

    # Table: granularity
    lines = []
    for r in rows("mc_granularity.csv"):
        if r["rho_case"] == "Basel" and float(r["annual_pd"]) in (0.03, 0.05, 0.10):
            n_loans = f"{int(r['n_loans']):,}".replace(",", "{,}")
            lines.append(f"{pct(r['annual_pd'], 0)}\\% & {n_loans} & {pct(r['asrf_q0.999'])}\\% & "
                         f"{pct(r['asrf_ga_q0.999'])}\\% & {pct(r['mc_q0.999'])}\\% [{pct(r['mc_q0.999_ci_lo'])}, {pct(r['mc_q0.999_ci_hi'])}]")
    write_tex("table_granularity.tex", lines)

    # Table: break-even premiums at a 15% hurdle
    be = rows("breakeven_premium.csv")
    lines = []
    for pd_ in ("0.03", "0.05", "0.1"):
        sel = [r for r in be if r["annual_pd"] == pd_ and float(r["hurdle"]) == 0.15]
        by = {r["rho_case"]: r for r in sel}
        b = by["Basel"]
        lines.append(f"{pct(pd_, 0)}\\% & {bps(b['s_star_bps'])} & {bps(by['0.05']['s_star_bps'])} & {bps(by['0.15']['s_star_bps'])} & "
                     f"{bps(by['0.3']['s_star_bps'])} & {bps(b['s_star_replenished_bps'])} & {bps(b['s_star_ga_n100_bps'])} & "
                     f"{bps(b['s_pool_u85_bps'])} & {bps(b['s_pool_u85_fee10_bps'])}")
    write_tex("table_premium.tex", lines)

    # Table: largest annual PD that 500 bps carries
    lines = []
    mp = rows("max_pd_for_500bps.csv")
    for case in ("Basel", "0.05", "0.15", "0.3"):
        sel = {r["hurdle"]: r for r in mp if r["rho_case"] == case}
        cells = [pct(sel[h]["max_annual_pd_loan_level"], 2) + "\\%" for h in ("0", "0.1", "0.15", "0.25") if h in sel]
        pool = pct(sel["0.15"]["max_annual_pd_pool_u85"], 2) + "\\%"
        label = "Basel" if case == "Basel" else f"${case}$"
        lines.append(f"{label} & " + " & ".join(cells) + f" & {pool}")
    write_tex("table_maxpd.tex", lines)

    # Table: recommended premium
    lines = []
    for r in rows("recommendation.csv"):
        if r["rho_case"] == "Basel":
            lines.append(f"{pct(r['pd'], 0)}\\% & {pct(r['loan_pd_30d'], 2)}\\% & {bps(r['s_loan_asrf_bps'])} & {bps(r['s_pool_asrf_bps'])} & "
                         f"{bps(r['s_pool_rep_ga_bps'])} & {bps(r['s_rec_bps'])} & {pct(r['apr'], 2)}\\%")
    write_tex("table_recommendation.tex", lines)

    # Table: reserve policies by year at annual PD 5% (this paper's simulation)
    ry = rows("reserve_years.csv", OUT)
    lines = []
    for case in ("expected loss", "recommended"):
        for policy in ("released above cap", "locked"):
            sel = {r["year"]: r for r in ry if r["annual_pd"] == "0.05" and r["reserve_share_case"] == case and r["policy"] == policy}
            share = pct(sel["1"]["reserve_share"], 0)
            cells = []
            for y in ("1", "5", "10", "30"):
                cells.append(f"{pct(sel[y]['mean_apy'], 2)}\\% & {pct(sel[y]['p_lender_loss'], 1)}\\%")
            lines.append(f"{share}\\%, {policy} & " + " & ".join(cells) + f" & {pct(sel['30']['mean_reserve'], 0)}\\%")
    write_tex("table_reserve_policy.tex", lines)

    # Curves: APY by year at PD 5%
    data = []
    for y in range(1, 31):
        row = [y]
        for case in ("expected loss", "recommended"):
            for policy in ("released above cap", "locked"):
                r = next(r for r in ry if r["annual_pd"] == "0.05" and r["reserve_share_case"] == case and r["policy"] == policy and r["year"] == str(y))
                row += [f"{100 * float(r['mean_apy']):.4f}", f"{100 * float(r['p_lender_loss']):.3f}"]
        data.append(row)
    write_csv("apy_by_year.csv", ["year", "el_rel_apy", "el_rel_p", "el_lock_apy", "el_lock_p", "rec_rel_apy", "rec_rel_p", "rec_lock_apy", "rec_lock_p"], data)

    # Curves: long-run sweep against r
    sw = rows("reserve_sweep.csv", OUT)
    rs = sorted({r["reserve_share"] for r in sw}, key=float)
    data = []
    for share in rs:
        row = [share]
        for pd_ in ("0.03", "0.05", "0.1"):
            r = next(r for r in sw if r["annual_pd"] == pd_ and r["reserve_share"] == share)
            row += [f"{100 * float(r['mean_apy_year_30']):.4f}", f"{100 * float(r['p_lender_loss_year_10']):.3f}", f"{100 * float(r['long_run_formula']):.4f}"]
        data.append(row)
    write_csv("reserve_sweep_curves.csv", ["r", "apy3", "p3", "f3", "apy5", "p5", "f5", "apy10", "p10", "f10"], data)

    # Curves: loss density at PD 5%
    x = np.linspace(0.0005, 0.30, 300)
    rho_b = vs.basel_other_retail_correlation(0.05)
    data = [[f"{100 * xi:.3f}", f"{float(vs.vasicek_pdf(xi, 0.05, rho_b)) / 100:.6f}", f"{float(vs.vasicek_pdf(xi, 0.05, 0.15)) / 100:.6f}"] for xi in x]
    write_csv("loss_density.csv", ["loss_pct", "basel", "rho015"], data)

    # Curves: break-even premium against PD at a 15% hurdle
    pds = np.geomspace(0.005, 0.20, 80)
    data = []
    for p in pds:
        row = [f"{100 * p:.4f}"]
        for rho in (None, 0.05, 0.15, 0.30):
            rr = vs.resolve_rho(p, rho)
            row.append(f"{10000 * float(vs.breakeven_premium(p, rr, 0.15)):.2f}")
        data.append(row)
    write_csv("premium_curve.csv", ["pd_pct", "basel", "rho005", "rho015", "rho030"], data)

    # Macros: the marginal per-loan PD under the factor model against the scalar conversion
    # (Proposition 1 holds conditionally on the factor; the marginal relationship is
    # PD = 1 - E[(1 - p_T(Z))^n], not 1 - (1 - E p_T(Z))^n).
    nodes, weights = np.polynomial.hermite_e.hermegauss(200)
    n = vs.cycles_per_year()
    macros = {}
    for rho, key in ((0.15, "High"), (float(vs.basel_other_retail_correlation(0.05)), "Basel")):
        p_year = np.clip(vs.conditional_pd(0.05, rho, nodes), 1e-15, 1 - 1e-15)
        p_loan = np.asarray(vs.loan_pd_from_annual_pd(p_year))
        marginal_loan = float(np.dot(weights, p_loan) / np.sqrt(2 * np.pi))
        macros[f"MarginalLoanPD{key}"] = f"{100 * marginal_loan:.4f}"
        macros[f"ScalarReconversion{key}"] = f"{100 * float(vs.annual_pd_from_loan_pd(marginal_loan)):.3f}"
    macros["HomogeneousLoanPD"] = f"{100 * float(vs.loan_pd_from_annual_pd(0.05)):.4f}"
    with open(OUT / "horizon_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print("wrote", sorted(p.name for p in OUT.iterdir()))


if __name__ == "__main__":
    main()
