#!/usr/bin/env python3
"""Does the 99% loss quantile of two pooled borrower cohorts exceed the sum of the cohorts' quantiles?

The reserve rule of Section 8 sizes the first-loss reserve from the 99% loss quantile of the whole
pool. A quantile is not subadditive in general: with discrete losses, the quantile of a sum can
exceed the sum of the quantiles, and with independent risks it can fall below it. This script
measures both effects for finite pools in the paper's own model. Two cohorts A and B of n loans
each, annual default probabilities (pA, pB), LGD 100%, one year, with the Basel other-retail
correlation of each PD. Borrower i of cohort c defaults if sqrt(rho_c) Z_c + sqrt(1 - rho_c) e_i <
Phi^{-1}(p_c). Three dependence structures: one common Gaussian factor Z_A = Z_B (the paper's model,
Section 4); independent factors (two unrelated markets); and one common Student-t factor with
nu = 10 (Section 7's alternative, same marginal PD). Losses are counted in defaulted loans, so the
sum of cohort quantiles and the pooled quantile are directly comparable. Expected shortfall, which is
subadditive, is reported next to the quantile.

Usage: python3 scripts/pooling_subadditivity.py <path to microcredit-contract>

Writes data/table_pooling.tex, data/pooling.csv and data/pooling_summary.tex.
"""
import csv
import pathlib
import sys

import numpy as np
from scipy.stats import chi2, norm, t as student

CONTRACT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../../microcredit-contract")
sys.path.insert(0, str(CONTRACT / "analysis/credit_risk"))
import vasicek as vs  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/pooling_subadditivity.py; do not edit.\n"
SEED = 20261006
PATHS = 400_000
NU = 10
SIZES = (50, 250)
PD_PAIRS = ((0.05, 0.05), (0.05, 0.20), (0.01, 0.20))
Q = 0.99


def defaults(n, pd, rho, z, w, rng):
    """Defaulted loans in a cohort of n, conditional on the factor draws z (and tail factor w)."""
    if w is None:
        threshold = norm.ppf(pd)
        p = norm.cdf((threshold - np.sqrt(rho) * z) / np.sqrt(1 - rho))
    else:
        p = norm.cdf((student.ppf(pd, NU) / np.sqrt(w) - np.sqrt(rho) * z) / np.sqrt(1 - rho))
    return rng.binomial(n, p)


def quantile_and_es(x, q):
    xq = float(np.quantile(x, q))
    tail = x[x >= xq]
    return xq, float(tail.mean())


def main():
    OUT.mkdir(exist_ok=True)
    rng = np.random.default_rng(np.random.SeedSequence([SEED, 11]))
    rows, lines, macros = [], [], {}
    worst_ratio = 0.0
    worst_label = ""
    for n in SIZES:
        for pa, pb in PD_PAIRS:
            ra, rb = float(vs.basel_other_retail_correlation(pa)), float(vs.basel_other_retail_correlation(pb))
            for structure in ("common", "independent", "t10"):
                za = rng.standard_normal(PATHS)
                zb = za if structure != "independent" else rng.standard_normal(PATHS)
                w = nu_w = None
                if structure == "t10":
                    w = NU / chi2.rvs(NU, size=PATHS, random_state=rng)
                da = defaults(n, pa, ra, za, w, rng)
                db = defaults(n, pb, rb, zb, w, rng)
                qa, ea = quantile_and_es(da, Q)
                qb, eb = quantile_and_es(db, Q)
                qs, es = quantile_and_es(da + db, Q)
                ratio_q = qs / (qa + qb)
                ratio_es = es / (ea + eb)
                rows.append({"n_per_cohort": n, "pd_a": pa, "pd_b": pb, "structure": structure,
                             "q99_a": qa, "q99_b": qb, "q99_pooled": qs, "ratio_q99": ratio_q,
                             "es99_a": ea, "es99_b": eb, "es99_pooled": es, "ratio_es99": ratio_es})
                label = {"common": "common Gaussian", "independent": "independent", "t10": "common $t_{10}$"}[structure]
                lines.append(f"{n} & {100 * pa:.0f}\\% & {100 * pb:.0f}\\% & {label} & {qa:.0f} & {qb:.0f} & {qs:.0f} & "
                             f"{ratio_q:.2f} & {ea:.1f} & {eb:.1f} & {es:.1f} & {ratio_es:.2f} \\\\")
                if structure != "independent" and ratio_q > worst_ratio:
                    worst_ratio, worst_label = ratio_q, f"{n} loans per cohort, PDs {100 * pa:.0f} and {100 * pb:.0f} percent, {label}"
                if structure == "common" and n == 50 and (pa, pb) == (0.05, 0.20):
                    macros["PoolFiftyMixedQ"] = f"{qs:.0f}"
                    macros["PoolFiftyMixedSum"] = f"{qa + qb:.0f}"
                    macros["PoolFiftyMixedRatio"] = f"{ratio_q:.2f}"
                    macros["PoolFiftyMixedESRatio"] = f"{ratio_es:.2f}"
                if structure == "independent" and n == 50 and (pa, pb) == (0.05, 0.05):
                    macros["PoolFiftyIndepRatio"] = f"{ratio_q:.2f}"
    max_es_ratio = max(r["ratio_es99"] for r in rows)
    macros["PoolMaxQRatio"] = f"{worst_ratio:.2f}"
    macros["PoolMaxESRatio"] = f"{max_es_ratio:.2f}"
    macros["PoolPaths"] = f"{PATHS:,}".replace(",", "{,}")
    with open(OUT / "pooling.csv", "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    with open(OUT / "table_pooling.tex", "w") as fh:
        fh.write(HEADER)
        fh.write("\n".join(lines) + "\n")
    with open(OUT / "pooling_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"{'n':>4} {'pdA':>4} {'pdB':>4} {'structure':>12} {'q99A':>5} {'q99B':>5} {'q99AB':>6} {'ratio':>6} "
          f"{'es99A':>6} {'es99B':>6} {'es99AB':>7} {'ratio':>6}")
    for r in rows:
        print(f"{r['n_per_cohort']:>4} {100 * r['pd_a']:>3.0f}% {100 * r['pd_b']:>3.0f}% {r['structure']:>12} "
              f"{r['q99_a']:>5.0f} {r['q99_b']:>5.0f} {r['q99_pooled']:>6.0f} {r['ratio_q99']:>6.2f} "
              f"{r['es99_a']:>6.1f} {r['es99_b']:>6.1f} {r['es99_pooled']:>7.1f} {r['ratio_es99']:>6.2f}")
    print(f"largest pooled/sum quantile ratio with a shared factor: {worst_ratio:.2f} ({worst_label}); "
          f"largest expected-shortfall ratio: {max_es_ratio:.2f}")


if __name__ == "__main__":
    main()
