#!/usr/bin/env python3
"""The loss tail under a Student-t common factor, against the Gaussian one-factor model (Section 7).

In the Gaussian model, borrower i defaults within the year if sqrt(rho) Z + sqrt(1 - rho) e_i falls
below Phi^{-1}(PD). The t-copula alternative multiplies the latent variable by sqrt(W), with
W = nu / chi^2_nu independent of (Z, e), and sets the threshold at the t_nu quantile of PD, so the
marginal PD is unchanged while defaults share a tail factor. Conditional on (W, Z) defaults are
independent with probability Phi((t_nu^{-1}(PD) / sqrt(W) - sqrt(rho) Z) / sqrt(1 - rho)), which
is the loss rate of the infinitely granular pool; its quantiles are estimated by Monte Carlo.

Usage: python3 scripts/tail_dependence.py <path to microcredit-contract>

Writes data/table_tail.tex and data/tail_summary.tex.
"""
import pathlib
import sys

import numpy as np
from scipy.stats import chi2, norm, t as student

CONTRACT = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parents[3] / "microcredit-contract"
sys.path.insert(0, str(CONTRACT / "analysis/credit_risk"))
import vasicek as vs  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/tail_dependence.py; do not edit.\n"
SEED = 20261005
PATHS = 2_000_000
NUS = (5, 10)


def t_factor_losses(pd, rho, nu, rng):
    z = rng.standard_normal(PATHS)
    w = nu / chi2.rvs(nu, size=PATHS, random_state=rng)
    return norm.cdf((student.ppf(pd, nu) / np.sqrt(w) - np.sqrt(rho) * z) / np.sqrt(1 - rho))


def main():
    OUT.mkdir(exist_ok=True)
    rng = np.random.default_rng(np.random.SeedSequence([SEED, 7]))
    lines = []
    macros = {}

    def pct(x, d=2):
        return f"{100 * float(x):.{d}f}"

    for pd in (0.05, 0.10):
        for rho_label, rho in (("Basel", float(vs.basel_other_retail_correlation(pd))), ("0.15", 0.15)):
            g99 = float(vs.vasicek_quantile(pd, rho, 0.99))
            g999 = float(vs.vasicek_quantile(pd, rho, 0.999))
            cells = [f"{pct(g99)}\\% & {pct(g999)}\\%"]
            for nu in NUS:
                d = t_factor_losses(pd, rho, nu, rng)
                q99, q999 = float(np.quantile(d, 0.99)), float(np.quantile(d, 0.999))
                mean = float(d.mean())
                cells.append(f"{pct(q99)}\\% & {pct(q999)}\\%")
                if pd == 0.05 and rho_label == "Basel":
                    key = {5: "Five", 10: "Ten"}[nu]
                    macros[f"TailT{key}Ratio"] = f"{q999 / g999:.2f}"
                    macros[f"TailT{key}Mean"] = pct(mean)
                    macros[f"TailT{key}QNinetyNine"] = pct(q99)
                    macros[f"TailT{key}Q"] = pct(q999)
                if pd == 0.05 and rho_label == "0.15":
                    key = {5: "Five", 10: "Ten"}[nu]
                    macros[f"TailT{key}RatioHigh"] = f"{q999 / g999:.2f}"
            label = "Basel" if rho_label == "Basel" else "$0.15$"
            lines.append(f"{pct(pd, 0)}\\% & {label} & " + " & ".join(cells) + " \\\\")
    macros["GaussQ"] = pct(float(vs.vasicek_quantile(0.05, float(vs.basel_other_retail_correlation(0.05)), 0.999)))
    macros["GaussQNinetyNine"] = pct(float(vs.vasicek_quantile(0.05, float(vs.basel_other_retail_correlation(0.05)), 0.99)))
    with open(OUT / "table_tail.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")
    with open(OUT / "tail_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(macros)


if __name__ == "__main__":
    main()
