#!/usr/bin/env python3
"""Tables and curves for the paper from the contract repository's liquidity experiments.

Reads analysis/liquidity/results/*.csv, written by analysis/liquidity/run.py at commit b725a85 of
https://github.com/scottonchain/microcredit-contract, and writes data/*.csv and data/table_*.tex.

Usage: python3 scripts/extract_liquidity.py <path to microcredit-contract>
"""
import csv
import pathlib
import sys

CONTRACT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../../microcredit-contract")
RES = CONTRACT / "analysis/liquidity/results"
OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/extract_liquidity.py; do not edit.\n"
FAMILIES = [("ws", "Watts--Strogatz"), ("ba", "Barab\\'asi--Albert"), ("sbm", "SBM, credit everywhere"),
            ("sbm-concentrated", "SBM, credit in half the blocks")]
REGIMES = ["one-hop", "2-hop", "3-hop", "unbounded", "centralised"]
BASE = {"n": "1000", "degree": "8", "rewiring": "0.1", "q": "0.2", "c": "25", "x": "50"}


def rows(name):
    return list(csv.DictReader(open(RES / name)))


def is_base(r, **override):
    want = dict(BASE, **override)
    return all(r.get(k) is None or _eq(r[k], v) for k, v in want.items())


def _eq(a, b):
    try:
        return abs(float(a) - float(b)) < 1e-9
    except ValueError:
        return a == b


def f2(x):
    return f"{float(x):.2f}"


def write_tex(name, lines):
    with open(OUT / name, "w") as fh:
        fh.write(HEADER)
        for line in lines:
            fh.write(line + " \\\\\n")


def write_csv(name, header, data):
    with open(OUT / name, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        w.writerows(data)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    families = {r["family"] for r in rows("static.csv")}
    fams = [(k, v) for k, v in FAMILIES if k in families]

    # Table: realistic gain at the base point (fresh and steady)
    real = {r["family"]: r for r in rows("realistic.csv")}
    lines_fresh, lines_steady = [], []
    for key, label in fams:
        r = real[key]
        lines_fresh.append(label + " & " + f2(r["static_p_one-hop-static"]) + " & " +
                           " & ".join(f2(r[f"static_p_{g}"]) for g in REGIMES) + " & " +
                           " / ".join(f"{float(r[f'static_mean_{g}']):.0f}" for g in ["one-hop", "2-hop", "3-hop", "unbounded"]))
        lines_steady.append(label + " & " + " & ".join(f2(r[f"steady_{g}"]) for g in REGIMES))
    write_tex("table_fresh.tex", lines_fresh)
    write_tex("table_steady.tex", lines_steady)

    # Table: who stands behind multi-hop loans (steady state, base point)
    st = rows("steady.csv")
    lines = []
    for key, label in fams:
        for g in ["2-hop", "3-hop", "unbounded"]:
            sel = [r for r in st if r["family"] == key and r["regime"] == g and is_base(r) and _eq(r["rho"], "0.5")]
            if not sel:
                continue
            r = sel[0]
            lines.append(f"{label} & {g} & {100 * float(r['routed_share']):.0f}\\% & {float(r['mean_hops']):.2f} & "
                         f"{100 * float(r['relayed_share']):.0f}\\% & {100 * float(r['remote_share']):.0f}\\% & "
                         f"{float(r['slots_routed']):.1f}")
    write_tex("table_liability.tex", lines)

    # Table: Sybil extraction (Watts-Strogatz, m = 1)
    sy = rows("sybil.csv")
    lines = []
    for r in sy:
        if r["family"] == "ws" and r["m"] == "1" and r["g"] in ("20", "50"):
            ends = {"random": "random accounts", "holders": "credit holders", "no credit": "accounts without credit"}.get(r["endpoints"], r["endpoints"])
            lines.append(f"{ends} & {r['g']} & {r['holder_endpoints']} & {float(r['g_times_c']):,.0f} & "
                         f"{float(r['one-hop']):,.0f} & {float(r['2-hop']):,.0f} & {float(r['3-hop']):,.0f} & "
                         f"{float(r['unbounded']):,.0f} & {float(r['path-liable']):,.0f}".replace(",", "{,}"))
    write_tex("table_sybil.tex", lines)
    invariant = all(
        len({r2["unbounded"] for r2 in sy if (r2["family"], r2["endpoints"], r2["g"]) == (r["family"], r["endpoints"], r["g"])}) == 1
        for r in sy)
    print("Sybil extraction identical across m:", invariant)

    # Curves: success against mean degree, fresh and steady, Watts-Strogatz and SBM half
    stat = rows("static.csv")
    for key in ("ws", "sbm-concentrated"):
        data = []
        for deg in ("4", "6", "8", "10", "12"):
            row = [deg]
            for g in REGIMES:
                s = [r for r in stat if r["family"] == key and r["regime"] == g and is_base(r, degree=deg)]
                row.append(f2(s[0]["p_borrow_x"]) if s else "nan")
            for g in REGIMES:
                s = [r for r in st if r["family"] == key and r["regime"] == g and is_base(r, degree=deg) and _eq(r["rho"], "0.5")]
                row.append(f2(s[0]["success"]) if s else "nan")
            data.append(row)
        write_csv(f"degree_{key.replace('-concentrated', '_half')}.csv", ["degree"] + [f"p_{g}" for g in REGIMES] + [f"s_{g}" for g in REGIMES], data)

    # Curves: P(maximum borrowable >= x), Watts-Strogatz base
    ba = [r for r in rows("borrowable_amount.csv") if r["family"] == "ws"]
    cols = ["one-hop-static", "one-hop", "2-hop", "3-hop", "unbounded"]
    write_csv("borrowable_ws.csv", ["x"] + cols, [[r["x"]] + [r[c] for c in cols] for r in ba])

    # Curves: issued credit one-hop needs (equivalence curve) and the multi-hop targets
    eq = rows("equivalence_curve.csv")
    write_csv("equivalence_curve.csv", ["q", "onehop_static", "onehop_steady"], [[r["q"], r["onehop_static"], r["onehop_steady"]] for r in eq])
    lines = []
    for r in rows("equivalence.csv"):
        lines.append(f"{r['regime']} & {f2(r['target_static'])} & {f2(r['q_onehop_static'])} & {float(r['issuance_multiple_static']):.1f}$\\times$ & "
                     f"{f2(r['target_steady'])} & {f2(r['q_onehop_steady'])} & {float(r['issuance_multiple_steady']):.1f}$\\times$")
    write_tex("table_equivalence.tex", lines)
    print("wrote", sorted(p.name for p in OUT.iterdir()))


if __name__ == "__main__":
    main()
