#!/usr/bin/env python3
"""Between-graph replication of the steady state, and a fixed-cohort equivalence (Section 5).

Reuses analysis/liquidity of the contract repository. Two experiments:

1. The steady-state task of run.py at the base point on three independent graphs (run.py uses one
   graph and five time batches), so that the success rates of Table 2 carry a between-network
   standard deviation. Replicate 0 is run.py's own graph and request sequence and reproduces its
   numbers exactly; replicates 1 and 2 draw a new graph, new holders and new requests.
2. A fixed-cohort equivalence: with the graph, the holders, the borrowers and the request process
   fixed at the base point, every holder's issued line and the trust per edge are scaled together
   by a multiple (a full line keeps backing four neighbours), and the multiple at which one hop
   reaches the two-hop, three-hop and unbounded success rates of the base point is reported.
   Scaling the line alone changes nothing under one hop, because a neighbour backs at most the
   trust per edge. Table 3 instead raises the holder share, which removes accounts from the
   borrower population and rescales the request process.

Usage: python3 scripts/steady_replicates.py <path to microcredit-contract>     (a few minutes)

Writes data/steady_replicates.csv, data/equivalence_line.csv, data/table_steady_replicates.tex,
data/table_equivalence_line.tex and data/replicates_summary.tex.
"""
import csv
import pathlib
import sys

import numpy as np

CONTRACT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../../microcredit-contract")
sys.path.insert(0, str(CONTRACT / "analysis/liquidity"))
import model as m  # noqa: E402
import run as R  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/steady_replicates.py; do not edit.\n"
REPLICATES = (0, 1, 2)
MULTIPLES = (1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 3.5, 4.0)
REGIMES = ("one-hop", "2-hop", "3-hop", "unbounded", "centralised")
TARGETS = ("2-hop", "3-hop", "unbounded")


def steady(s, regime, replicate, request_setting=None, duration=None):
    """run.py's task_steady with the graph replicate as a parameter, an optional fixed duration and
    an optional setting from which the request sequence is seeded (so that settings that differ
    only in the issued line face the same requests)."""
    net = R.population(s, replicate)
    duration = R.mean_duration(s) if duration is None else duration
    warmup = int(max(3 * duration, 300))
    rs = s if request_setting is None else request_setting
    parts = [v for k, v in rs.items() if k != "duration"]
    if replicate:
        parts.append(replicate)
    rng = np.random.default_rng(R.seed_of("requests", *parts))
    who, durations = m.request_sequence(warmup + R.STEADY_MEASURED, np.flatnonzero(net.credit == 0), duration, rng)
    res = m.simulate(net, regime, who, durations, s["x"])
    return float(res.success[warmup:].mean())


def main():
    OUT.mkdir(exist_ok=True)
    base = R.setting()
    macros = {}

    # 1. Replication across graphs.
    published = {}
    for row in csv.DictReader(open(CONTRACT / "analysis/liquidity/results/steady.csv")):
        if all(abs(float(row[k]) - float(base[k])) < 1e-9 for k in ("n", "degree", "rewiring", "q", "c", "x", "rho")) \
                and row["family"] == base["family"]:
            published[row["regime"]] = float(row["success"])
    rows = []
    for regime in REGIMES:
        succ = [steady(base, regime, rep) for rep in REPLICATES]
        assert abs(succ[0] - published[regime]) < 1e-9, (regime, succ[0], published[regime])
        rows.append({"regime": regime, **{f"graph{rep}": succ[i] for i, rep in enumerate(REPLICATES)},
                     "mean": float(np.mean(succ)), "sd": float(np.std(succ, ddof=1))})
    with open(OUT / "steady_replicates.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    lines = [f"{r['regime']} & " + " & ".join(f"{r[f'graph{rep}']:.3f}" for rep in REPLICATES)
             + f" & {r['mean']:.3f} & {r['sd']:.3f} \\\\" for r in rows]
    with open(OUT / "table_steady_replicates.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")
    by = {r["regime"]: r for r in rows}
    macros["SteadySdMax"] = f"{max(r['sd'] for r in rows):.3f}"
    macros["SteadySdOneHop"] = f"{by['one-hop']['sd']:.3f}"
    macros["SteadyMeanOneHop"] = f"{by['one-hop']['mean']:.3f}"
    macros["SteadyMeanTwoHop"] = f"{by['2-hop']['mean']:.3f}"
    ratios = [by["2-hop"][f"graph{rep}"] / by["one-hop"][f"graph{rep}"] for rep in REPLICATES]
    macros["TwoHopRatioMin"] = f"{min(ratios):.2f}"
    macros["TwoHopRatioMax"] = f"{max(ratios):.2f}"

    # 2. Fixed-cohort equivalence: scale every holder's line and the trust per edge together, on
    # the same graph, holders and requests.
    duration = R.mean_duration(base)
    succ = []
    for mult in MULTIPLES:
        s = R.setting(line=base["line"] * mult, c=base["c"] * mult)
        succ.append(steady(s, "one-hop", 0, request_setting=base, duration=duration))
    succ = np.array(succ)
    with open(OUT / "equivalence_line.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["multiple", "line", "trust_per_edge", "one_hop_success"])
        for mult, v in zip(MULTIPLES, succ):
            w.writerow([mult, base["line"] * mult, base["c"] * mult, f"{v:.6g}"])
    for regime in TARGETS:
        target = published[regime]
        need = R.first_q_reaching(np.array(MULTIPLES), succ, target)
        key = {"2-hop": "Two", "3-hop": "Three", "unbounded": "Unb"}[regime]
        macros[f"LineMult{key}"] = f"$>{MULTIPLES[-1]:.0f}$" if np.isnan(need) else f"{need:.1f}"
        macros[f"Target{key}"] = f"{target:.3f}"
    lines = [f"{mult:g} & {base['line'] * mult:.0f} & {base['c'] * mult:.1f} & {v:.3f} \\\\" for mult, v in zip(MULTIPLES, succ)]
    with open(OUT / "table_equivalence_line.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")
    macros["OneHopAtBase"] = f"{succ[0]:.3f}"
    macros["OneHopBelowDouble"] = f"{succ[list(MULTIPLES).index(1.75)]:.3f}"
    macros["OneHopAtDouble"] = f"{succ[list(MULTIPLES).index(2.0)]:.3f}"
    macros["OneHopAtQuadruple"] = f"{succ[-1]:.3f}"
    with open(OUT / "replicates_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(macros)


if __name__ == "__main__":
    main()
