#!/usr/bin/env python3
"""Extract the attack-simulation data used in Section 8 of the paper.

Reads results/attacks.csv written by analysis/sybil_sim/run.py in the contract repository
(https://github.com/scottonchain/microcredit-contract, commit b725a85) and writes:

  data/attack_profit.csv   attacker net profit against the number of accounts (Figure 6)
  data/attack_table.tex    the rows of Table 2

Usage: python3 scripts/extract_simulation.py <path to microcredit-contract>
"""
import csv
import pathlib
import sys

MECHANISMS = [
    ("M0 pagerank_vouch", "PageRank"),
    ("M1 hermes_history", "25\\% rule"),
    ("M3 conservation_dues", "Net-interest dues"),
    ("M3r conservation_reserve_dues", "Reserve dues"),
]
ROWS = [
    ("A1 ring", "pure ring", "Ring of new accounts"),
    ("A3 deposit roots", "pure ring", "Ring on withdrawn deposits"),
    ("A4 wash farm", "stake seed, grace repayment, 4 cycles", "Recycled stake, no interest"),
    ("A4 wash farm", "stake seed, 30-day repayment, 4 cycles", "Recycled stake, 30-day loans"),
    ("A5 collusive backer", "", "Colluding backer, line 100"),
    ("A7 self-lending dues", "lender share 50%", "Borrower who lends, $s=0.5$"),
]
SERIES = [
    ("pagerank_rootring", "M0 pagerank_vouch", "A3 deposit roots", "pure ring"),
    ("implemented_rootring", "M3r conservation_reserve_dues", "A3 deposit roots", "pure ring"),
    ("rule25_seed", "M1 hermes_history", "A4 wash farm", "stake seed, grace repayment, 4 cycles"),
    ("implemented_seed", "M3r conservation_reserve_dues", "A4 wash farm", "stake seed, grace repayment, 4 cycles"),
    ("netdues_lender", "M3 conservation_dues", "A7 self-lending dues", "lender share 50%"),
    ("implemented_lender", "M3r conservation_reserve_dues", "A7 self-lending dues", "lender share 50%"),
]


def main() -> None:
    repo = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../../microcredit-contract")
    rows = list(csv.DictReader(open(repo / "analysis/sybil_sim/results/attacks.csv")))
    profit = {}
    for r in rows:
        if r["world"] == "demo":
            profit[(r["mechanism"], r["attack"], r["variant"], int(r["n"]))] = float(r["net_profit"])

    out = pathlib.Path(__file__).resolve().parent.parent / "data"
    out.mkdir(exist_ok=True)

    ns = sorted({k[3] for k in profit})
    with open(out / "attack_profit.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["n"] + [s[0] for s in SERIES])
        for n in ns:
            w.writerow([n] + [f"{profit[(m, a, v, n)]:.2f}" for _, m, a, v in SERIES])

    def cell(m, a, v, n):
        key = (m, a, v, n)
        if key not in profit:
            return "n/a"
        x = profit[key]
        s = f"{abs(x):,.2f}".replace(",", "{,}")
        return ("$-$" if x < -0.005 else "") + s

    with open(out / "attack_table.tex", "w") as fh:
        fh.write("% Generated by scripts/extract_simulation.py; do not edit.\n")
        for a, v, label in ROWS:
            cells = []
            for m, _ in MECHANISMS:
                cells.append(cell(m, a, v, 1))
                cells.append(cell(m, a, v, 64))
            fh.write(label + " & " + " & ".join(cells) + " \\\\\n")
    print(f"wrote {out / 'attack_profit.csv'} and {out / 'attack_table.tex'}")


if __name__ == "__main__":
    main()
