#!/usr/bin/env python3
"""Write Table 2 and the sentence that summarise data/mutation.csv (Section 8.3).

Outputs data/mutation_table.tex and data/mutation_summary.tex.
"""
import csv
import pathlib

# invariant function -> reference in the paper
PROPERTIES = {
    "invariant_I1_capacityBound": "Thm.~\\ref{thm:capacity}",
    "invariant_I1b_lostCreditBacksNobody": "coverage",
    "invariant_Q_perAccountCreditBudget": "Lem.~\\ref{lem:Q}",
    "invariant_I2_lossBound": "Thm.~\\ref{thm:loss}",
    "invariant_I8_honestLendersPayOnlyForIssuedLines": "Cor.~\\ref{cor:reserve}",
    "invariant_I3_sybilIndependence": "Sybil gain",
    "invariant_I4_sybilsCommitNothingTheyDidNotPay": "Sybil commitments",
    "invariant_I5_solvency": "solvency",
    "invariant_I6_lenderClaims": "lender claims",
    "invariant_I7_impairment": "provisions",
    "invariant_creditLedgers": "credit ledgers",
    "invariant_poolLedgers": "pool ledgers",
    "invariant_handlerHealth": "model agreement",
}

WORDS = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
         "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen"]


def word(n: int) -> str:
    return WORDS[n] if n < len(WORDS) else str(n)


def main() -> None:
    data = pathlib.Path(__file__).resolve().parent.parent / "data"
    with (data / "mutation.csv").open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise SystemExit("mutation.csv contains no experiments")
    total = len(rows)
    seeds = int(rows[0]["seeds"])
    if seeds <= 0 or any(int(r["seeds"]) != seeds or not 0 <= int(r["seeds_detecting"]) <= seeds for r in rows):
        raise SystemExit("mutation.csv has inconsistent seed counts; no summary was written")
    if any(r["status"] not in {"detected by fuzzing", "detected by unit tests", "not detected"} for r in rows):
        raise SystemExit("mutation.csv contains an incomplete experiment; do not report it as an undetected fault")
    every = sum(int(r["seeds_detecting"]) == seeds for r in rows)
    some = sum(0 < int(r["seeds_detecting"]) < seeds for r in rows)
    unit = sum(int(r["seeds_detecting"]) == 0 and bool(r["failed_unit_tests"]) for r in rows)
    missed = total - every - some - unit

    parts = [f"Fuzzing detected {word(every)} of the {word(total)} faults under every seed"]
    if some:
        parts[0] += f", and {word(some)} more under some seeds but not all"
    parts[0] += "."
    if unit:
        parts.append(f"The unit tests detected the remaining {word(unit)}." if not missed
                     else f"The unit tests detected {word(unit)} of the rest.")
    if missed:
        parts.append(f"{word(missed).capitalize()} went undetected.")
    with open(data / "mutation_table.tex", "w") as fh:
        fh.write("% Generated by scripts/mutation_summary.py from data/mutation.csv; do not edit.\n")
        for r in rows:
            failed = r["failed_properties"].split()
            unit_failed = r["failed_unit_tests"].split()
            if failed:
                cell = ", ".join(PROPERTIES.get(f, f.replace("_", "\\_")) for f in failed)
            elif unit_failed:
                cell = ("unit tests: " if len(unit_failed) > 1 else "unit test: ") + ", ".join(
                    "\\texttt{\\seqsplit{" + n + "}}" for n in unit_failed)
            else:
                cell = r["status"]
            fh.write(f"{r['description']} & {r['seeds_detecting']}/{r['seeds']} & {cell} \\\\\n")
    with open(data / "mutation_summary.tex", "w") as fh:
        fh.write("% Generated by scripts/mutation_summary.py; do not edit.\n")
        fh.write("\\newcommand{\\MutationSummary}{" + " ".join(parts) + "}\n")
    print(" ".join(parts))


if __name__ == "__main__":
    main()
