#!/usr/bin/env python3
"""Summarise a stateful fuzzing campaign of the contract's credit invariants (Section 8.2).

The campaign is test/invariant/CreditConservation.invariant.t.sol in the contract repository,
run with its inline settings raised to `runs = 1300` and `depth = 256` and with
INVARIANT_STATS_FILE set, so that afterInvariant appends one line per run:

    INVARIANT_STATS_FILE=./inv_stats.txt forge test --match-path 'test/invariant/*' | tee forge.log

Usage: python3 scripts/summarize_fuzz.py <inv_stats.txt> <forge.log> <runs per test> <depth>

Writes data/fuzz_stats.tex (macros used by paper.tex) and data/fuzz_summary.csv.
"""
import csv
import pathlib
import re
import sys

COUNTERS = ["loans", "defaults", "slashing", "charging", "residual", "sybilDefaults",
            "sybilLoans", "sybilBacksOk", "sybilBacksRejected", "impairments"]


def fmt(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def main() -> None:
    stats_path, log_path, runs, depth = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4])
    totals = {k: 0 for k in COUNTERS}
    calls = 0
    max_q = 0
    max_i = 0
    lines = 0
    # Forge calls afterInvariant once more after each campaign's last run, which appends a copy of
    # that run's line, so exact duplicates are dropped; the count is checked against tests x runs.
    for line in dict.fromkeys(open(stats_path)):
        fields = dict(tok.split("=", 1) for tok in line.split() if "=" in tok)
        if "loans" not in fields:
            continue
        lines += 1
        for k in COUNTERS:
            totals[k] += int(fields[k])
        max_q = max(max_q, int(fields["maxQbps"]))
        max_i = max(max_i, int(fields["I2bps"]))
        for k, v in fields.items():
            if "/" in v:
                calls += sum(int(x) for x in v.split("/"))

    log = open(log_path).read()
    summary = re.findall(r"(\d+) passed; (\d+) failed", log)
    if not summary:
        sys.exit("no forge summary line in the log")
    passed, failed = (int(x) for x in summary[-1])
    if failed:
        sys.exit(f"the campaign has {failed} failing tests; the paper reports a clean campaign only")
    if lines != passed * runs:
        sys.exit(f"{lines} stats lines but {passed} tests x {runs} runs; the campaign is incomplete")

    out = pathlib.Path(__file__).resolve().parent.parent / "data"
    out.mkdir(exist_ok=True)
    macros = {
        "FuzzTests": str(passed),
        "FuzzRunsPerTest": fmt(runs),
        "FuzzDepth": str(depth),
        "FuzzCallsText": fmt(calls),
        "FuzzLoans": fmt(totals["loans"]),
        "FuzzDefaults": fmt(totals["defaults"]),
        "FuzzSlashing": fmt(totals["slashing"]),
        "FuzzCharging": fmt(totals["charging"]),
        "FuzzResidual": fmt(totals["residual"]),
        "FuzzSybilLoans": fmt(totals["sybilLoans"]),
        "FuzzSybilDefaults": fmt(totals["sybilDefaults"]),
        "FuzzSybilBacksOk": fmt(totals["sybilBacksOk"]),
        "FuzzSybilBacksRejected": fmt(totals["sybilBacksRejected"]),
        "FuzzMaxQ": f"{max_q / 100:.2f}",
        "FuzzMaxI": f"{max_i / 100:.2f}",
    }
    with open(out / "fuzz_stats.tex", "w") as fh:
        fh.write("% Generated by scripts/summarize_fuzz.py; do not edit.\n")
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    with open(out / "fuzz_summary.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["tests", "runs_per_test", "depth", "calls", "stats_lines", "max_q_bps", "max_loss_bound_bps"] + COUNTERS)
        w.writerow([passed, runs, depth, calls, lines, max_q, max_i] + [totals[k] for k in COUNTERS])
    print(macros)


if __name__ == "__main__":
    main()
