#!/usr/bin/env python3
"""Tables and curves for the paper from the contract repository's issuer-policy experiments.

Reads analysis/issuer_policy/results/*.csv, written by analysis/issuer_policy/run.py at commit
b725a85 of https://github.com/scottonchain/microcredit-contract, and writes data/*.

Usage: python3 scripts/extract_issuer_policy.py <path to microcredit-contract>
"""
import math
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))
from paper_support import PaperTables

CONTRACT = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parents[3] / "microcredit-contract"
RES = CONTRACT / "analysis/issuer_policy/results"
OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/extract_issuer_policy.py; do not edit.\n"
tables = PaperTables(OUT, RES, HEADER)
rows, write_tex, write_csv = tables.read, tables.write_tex, tables.write_csv


def num(x, d=0):
    return f"{float(x):,.{d}f}".replace(",", "{,}").replace("-", "$-$")


def objective_table() -> None:
    """The surrogate objective of Proposition 2 against the cash-flow objective
    (1 - p) i mu (1 - e^{-l/mu}) - p l, whose optimum is mu ln((1 - p) i / p), at each tier's
    prior PD per cycle (Section 5)."""
    sys.path.insert(0, str(CONTRACT / "analysis/issuer_policy"))
    import policy as pol  # noqa: E402
    params = pol.PolicyParams()
    mu, i = params.demand_mean, params.premium_per_cycle
    lines, macros = [], {}
    worst_abs = worst_rel = 0.0
    for r in rows("tiers.csv"):
        p = pol.cycle_pd(float(r["prior_annual_pd"]))
        surrogate = mu * math.log(i / p) if p < i else 0.0
        exact = mu * math.log((1 - p) * i / p) if (1 - p) * i > p else 0.0
        shift = exact - surrogate
        rel = shift / surrogate if surrogate > 0 else 0.0
        worst_abs, worst_rel = max(worst_abs, abs(shift)), max(worst_rel, abs(rel))
        lines.append(f"{r['tier']} & {100 * p:.2f}\\% & {surrogate:.2f} & {exact:.2f} & {shift:+.2f} & {100 * rel:+.1f}\\%")
        key = {"basic": "Basic", "standard": "Standard", "enhanced": "Enhanced"}[r["tier"]]
        macros[f"LineShift{key}"] = f"{shift:+.2f}"
        macros[f"LineShiftRel{key}"] = f"{100 * rel:+.1f}"
    write_tex("table_objective.tex", lines)
    macros["LineShiftMaxAbs"] = f"{worst_abs:.2f}"
    macros["LineShiftMaxRel"] = f"{100 * worst_rel:.1f}"
    macros["PremiumPerCycle"] = f"{100 * i:.3f}"
    macros["DemandMean"] = f"{mu:.0f}"
    with open(OUT / "objective_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")


def main() -> None:
    OUT.mkdir(exist_ok=True)
    objective_table()

    lines = []
    for r in rows("tiers.csv"):
        lines.append(f"{r['tier']} & {num(r['identity_cost_usdc'])} & {num(r['cap_usdc'])} & "
                     f"{float(r['prior_strength_trials']):.0f} & {100 * float(r['prior_annual_pd']):.1f}\\% & "
                     f"{num(r['start_line_usdc'], 1)} & {num(r['line_after_24_trials_usdc'], 1)}")
    write_tex("table_tiers.tex", lines)

    lines = []
    for r in rows("evidence_routes.csv"):
        per = r["interest_per_trial_usdc"]
        per = "none" if per in ("inf", "nan") else num(per, 2)
        lines.append(f"{r['route']} & {float(r['good_weight']):g} & {float(r['bad_weight']):g} & {per}")
    write_tex("table_routes.tex", lines)

    lines = []
    for r in rows("budget_sweep.csv"):
        lines.append(f"{num(r['budget_usdc'])} & {num(r['mean_total_held_usdc'])} & {num(r['mean_exposure_usdc'])} & "
                     f"{100 * float(r['loss_rate_per_exposure_year']):.2f}\\% & {100 * float(r['loss_per_budget_year']):.2f}\\% & "
                     f"{100 * float(r['line_weighted_true_pd']):.2f}\\% & {num(r['issuer_profit_usdc'])} & {num(r['model_expected_profit_usdc'])}")
    write_tex("table_budget.tex", lines)

    ap = rows("attacker_profit.csv")
    tiers = {r["tier"]: r for r in rows("tiers.csv")}
    lines = []
    for t in ("basic", "standard", "enhanced"):
        r1 = next(r for r in ap if r["tier"] == t and r["identities"] == "1")
        r64 = next(r for r in ap if r["tier"] == t and r["identities"] == "64")
        lines.append(f"{t} & {num(tiers[t]['identity_cost_usdc'])} & {num(tiers[t]['cap_usdc'])} & {num(r1['mean_line_at_bust_usdc'], 1)} & "
                     f"{num(r1['profit_ic_usdc'], 1)} & {num(r1['profit_violated_usdc'], 1)} & {num(r64['loss_on_issued_lines_usdc'])} & "
                     f"{num(r64['byzantine_bound_usdc'])}")
    write_tex("table_attack.tex", lines)

    data = []
    for i in sorted({int(r["identities"]) for r in ap}):
        row = [i]
        for t in ("basic", "standard", "enhanced"):
            r = next(r for r in ap if r["tier"] == t and int(r["identities"]) == i)
            row += [f"{float(r['profit_ic_usdc']):.2f}", f"{float(r['profit_violated_usdc']):.2f}"]
        data.append(row)
    write_csv("attacker_curves.csv", ["identities", "basic_ic", "basic_viol", "standard_ic", "standard_viol", "enhanced_ic", "enhanced_viol"], data)

    hl = rows("honest_lines.csv")
    pds = ["0.01", "0.02", "0.05", "0.1", "0.2"]
    data = []
    for m in sorted({int(r["month"]) for r in hl}):
        row = [m]
        for p in pds:
            r = next(r for r in hl if int(r["month"]) == m and r["true_annual_pd"] == p)
            row.append(f"{float(r['mean_line_alive_usdc']):.3f}")
        data.append(row)
    write_csv("honest_lines.csv", ["month", "pd1", "pd2", "pd5", "pd10", "pd20"], data)
    lines = []
    for p in pds:
        cells = []
        for m in (0, 6, 12, 23):
            r = next(r for r in hl if int(r["month"]) == m and r["true_annual_pd"] == p)
            cells.append(num(r["mean_line_alive_usdc"], 1))
        r23 = next(r for r in hl if int(r["month"]) == 23 and r["true_annual_pd"] == p)
        lines.append(f"{100 * float(p):g}\\% & " + " & ".join(cells) + f" & {100 * float(r23['alive_share']):.1f}\\%")
    write_tex("table_lines.tex", lines)

    cal = [r for r in rows("calibration.csv") if r["bin"] != "all"]
    write_csv("calibration.csv", ["bin", "predicted", "true", "realised", "lo", "hi"],
              [[r["bin"], f"{100 * float(r['mean_predicted_cycle_pd']):.4f}", f"{100 * float(r['mean_true_cycle_pd']):.4f}",
                f"{100 * float(r['realised_default_rate']):.4f}", f"{100 * float(r['ci95_low']):.4f}", f"{100 * float(r['ci95_high']):.4f}"] for r in cal])
    allrow = next(r for r in rows("calibration.csv") if r["bin"] == "all")
    with open(OUT / "calibration_summary.tex", "w") as fh:
        fh.write(HEADER)
        fh.write(f"\\newcommand{{\\CalCycles}}{{{num(allrow['cycles'])}}}\n")
        fh.write(f"\\newcommand{{\\CalDefaults}}{{{allrow['defaults']}}}\n")
        fh.write(f"\\newcommand{{\\CalPredicted}}{{{100 * float(allrow['mean_predicted_cycle_pd']):.2f}}}\n")
        fh.write(f"\\newcommand{{\\CalTrue}}{{{100 * float(allrow['mean_true_cycle_pd']):.2f}}}\n")
        fh.write(f"\\newcommand{{\\CalRealised}}{{{100 * float(allrow['realised_default_rate']):.2f}}}\n")
        fh.write(f"\\newcommand{{\\CalLo}}{{{100 * float(allrow['ci95_low']):.2f}}}\n")
        fh.write(f"\\newcommand{{\\CalHi}}{{{100 * float(allrow['ci95_high']):.2f}}}\n")
    print("wrote", sorted(p.name for p in OUT.iterdir()))


if __name__ == "__main__":
    main()
