#!/usr/bin/env python3
"""Scoring variants under misspecified worlds (Section 7, "Validation under misspecification").

Reuses analysis/issuer_policy of the contract repository. Three scoring rules are run on the same
borrower paths in five worlds, three seeds each:

  scoring  weighted    the policy as proposed (evidence weighted by recency, unsecured size and
                       time at risk; zero for interest-free and fully secured loans)
           unweighted  every repaid loan is one trial, good or bad, whatever it put at risk
           tier only   the tier's prior alone, no repayment evidence

  world    as assumed            the population the priors were fitted to; lateness at the ratio
                                 the policy assumes
           riskier population    within every tier, more of the population at the high PDs than
                                 the prior assumes
           lateness halved       late repayments at half the assumed ratio to defaults
           lateness doubled      at twice the assumed ratio
           risk doubles, mo. 12  every borrower's default and late probabilities double from
                                 month 12 (a regime shift the prior does not know)

Reported per (world, scoring), mean of three seeds: the Brier score of the predicted cycle default
probability against the realised default, its skill against the realised base rate, the ratio of
realised to predicted defaults (all cycles, months 12 to 23, and weighted by the line), a cluster
bootstrap interval over borrowers for the Brier score, the honest loss rate per exposure-year, the
mean line of surviving borrowers at the last report, and the line that a bought identity running
the recycled-seed farm holds at the end.

Usage: python3 scripts/misspecification.py <path to microcredit-contract>     (a few minutes)

Writes data/misspecification.csv, data/table_misspecification.tex, data/table_misspecification_lines.tex
and data/misspecification_summary.tex.
"""
import csv
import pathlib
import sys

import numpy as np

CONTRACT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../../microcredit-contract")
sys.path.insert(0, str(CONTRACT / "analysis/issuer_policy"))
import policy as pol  # noqa: E402
import simulate as sim  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/misspecification.py; do not edit.\n"
SEEDS = (0, 1, 2)
CONFIG = dict(n_honest=600, budget_lines=150.0, increase_lines=40.0, n_farm=2)
BOOT = 200
ASSUMED_WEIGHTS = dict(pol.TIER_PD_WEIGHTS)
RISKIER_WEIGHTS = {
    "basic": (0.05, 0.15, 0.30, 0.25, 0.25),
    "standard": (0.10, 0.25, 0.30, 0.20, 0.15),
    "enhanced": (0.20, 0.35, 0.25, 0.12, 0.08),
}
POLICY = pol.PolicyParams()        # priors fitted to the assumed population and lateness
ORIGINAL_EVIDENCE = pol.evidence


def unweighted(view, now, params):
    good = bad = 0.0
    for loan in view.loans:
        if loan.status != pol.LoanStatus.REPAID or loan.closed_at is None:
            continue
        if loan.closed_at > loan.due_at:
            bad += 1.0
        else:
            good += 1.0
    return good, bad


def tier_only(view, now, params):
    return 0.0, 0.0


SCORINGS = (("weighted", ORIGINAL_EVIDENCE), ("unweighted", unweighted), ("tier only", tier_only))


class ShiftedSimulation(sim.Simulation):
    """Every honest borrower's default and late probabilities double from month 12."""

    def _honest_borrow(self, h, at, m):
        if m < 12:
            return super()._honest_borrow(h, at, m)
        p_d, p_l = h.p_default, h.p_late
        h.p_default, h.p_late = min(1.0, 2 * p_d), min(1.0, 2 * p_l)
        try:
            return super()._honest_borrow(h, at, m)
        finally:
            h.p_default, h.p_late = p_d, p_l


WORLDS = (
    # name, weights of the population, world late ratio, simulation class
    ("as assumed", ASSUMED_WEIGHTS, 2.0, sim.Simulation),
    ("riskier population", RISKIER_WEIGHTS, 2.0, sim.Simulation),
    ("lateness halved", ASSUMED_WEIGHTS, 1.0, sim.Simulation),
    ("lateness doubled", ASSUMED_WEIGHTS, 4.0, sim.Simulation),
    ("risk doubles, month 12", ASSUMED_WEIGHTS, 2.0, ShiftedSimulation),
)


def run_one(weights, late_ratio, cls, scoring_fn, seed):
    """One simulation: the world draws its borrowers with `weights` and `late_ratio`; the policy
    keeps its own priors and its assumed ratio; the scoring rule is `scoring_fn`."""
    pol.TIER_PD_WEIGHTS = weights
    world = pol.PolicyParams(late_ratio=late_ratio)
    try:
        s = cls(sim.SimConfig(seed=seed, params=world, **CONFIG))
    finally:
        pol.TIER_PD_WEIGHTS = ASSUMED_WEIGHTS
    s.p = POLICY                       # the issuer plans with the assumed priors and ratio
    pol.evidence = scoring_fn
    try:
        res = s.run()
    finally:
        pol.evidence = ORIGINAL_EVIDENCE
    farm_line = s.provider.score(s.verified_farm) * POLICY.max_loan_usdc / pol.SCALE
    return res, farm_line


def metrics(res, farm_line, rng):
    c = np.array([(x[0], x[1], x[2], x[4]) for x in res.cycles], dtype=float)
    month, idx, pred, y = c[:, 0], c[:, 1].astype(int), c[:, 2], c[:, 3]
    pred = np.nan_to_num(pred, nan=float(np.nanmean(pred)))
    brier = float(np.mean((pred - y) ** 2))
    base = float(y.mean())
    brier_base = float(np.mean((base - y) ** 2))
    skill = 1.0 - brier / brier_base if brier_base > 0 else 0.0
    # cluster bootstrap over borrowers
    borrowers = np.unique(idx)
    groups = {b: np.flatnonzero(idx == b) for b in borrowers}
    boots = []
    for _ in range(BOOT):
        pick = rng.choice(borrowers, size=len(borrowers), replace=True)
        sel = np.concatenate([groups[b] for b in pick])
        boots.append(float(np.mean((pred[sel] - y[sel]) ** 2)))
    lo, hi = float(np.quantile(boots, 0.025)), float(np.quantile(boots, 0.975))
    late = month >= 12
    lines_at = res.lines[month.astype(int), idx]
    w = np.maximum(lines_at, 0.0)
    ratio_all = float(y.sum() / pred.sum())
    ratio_late = float(y[late].sum() / pred[late].sum()) if late.any() else float("nan")
    ratio_w = float((w * y).sum() / (w * pred).sum()) if w.sum() > 0 else float("nan")
    months = [r for r in res.monthly if "exposure_usdc" in r]
    loss = sum(r["loss_honest_usdc"] for r in res.monthly)
    exposure_years = float(np.mean([r["exposure_usdc"] for r in months])) * res.config.months / 12
    alive = res.alive[-1]
    mean_line = float(res.lines[-1][alive].mean()) if alive.any() else float("nan")
    return {
        "cycles": len(y), "defaults": int(y.sum()), "brier": brier, "brier_lo": lo, "brier_hi": hi,
        "skill": skill, "ratio_all": ratio_all, "ratio_late": ratio_late, "ratio_weighted": ratio_w,
        "loss_rate": loss / exposure_years if exposure_years > 0 else float("nan"),
        "mean_line_end": mean_line, "farm_line": farm_line,
    }


def main():
    OUT.mkdir(exist_ok=True)
    rng = np.random.default_rng(np.random.SeedSequence([sim.BASE_SEED, 99]))
    rows = []
    for wname, weights, late_ratio, cls in WORLDS:
        for sname, fn in SCORINGS:
            per = []
            for seed in SEEDS:
                res, farm_line = run_one(weights, late_ratio, cls, fn, seed)
                per.append(metrics(res, farm_line, rng))
            agg = {k: float(np.mean([p[k] for p in per])) for k in per[0]}
            rows.append({"world": wname, "scoring": sname, "seeds": len(SEEDS), **agg})
            print(wname, sname, {k: round(v, 4) for k, v in agg.items()})
    with open(OUT / "misspecification.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    def pct(x, d=2):
        return f"{100 * x:.{d}f}"

    lines = []
    for r in rows:
        lines.append(
            f"{r['world']} & {r['scoring']} & {pct(r['brier'], 3)} [{pct(r['brier_lo'], 3)}, {pct(r['brier_hi'], 3)}] & "
            f"{pct(r['skill'], 1)}\\% & {r['ratio_all']:.2f} & {r['ratio_late']:.2f} & {r['ratio_weighted']:.2f} \\\\"
        )
    with open(OUT / "table_misspecification.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")
    lines = []
    for r in rows:
        lines.append(f"{r['world']} & {r['scoring']} & {pct(r['loss_rate'])}\\% & {r['mean_line_end']:.1f} & {r['farm_line']:.2f} \\\\")
    with open(OUT / "table_misspecification_lines.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")

    by = {(r["world"], r["scoring"]): r for r in rows}
    macros = {}
    for sname, key in (("weighted", "Weighted"), ("unweighted", "Unweighted"), ("tier only", "TierOnly")):
        a = by[("as assumed", sname)]
        macros[f"Brier{key}Assumed"] = pct(a["brier"], 3)
        macros[f"Skill{key}Assumed"] = pct(a["skill"], 1)
        macros[f"Ratio{key}Assumed"] = f"{a['ratio_all']:.2f}"
        macros[f"FarmLine{key}"] = f"{a['farm_line']:.2f}"
        macros[f"MeanLine{key}Assumed"] = f"{a['mean_line_end']:.1f}"
    for wname, key in (("riskier population", "Riskier"), ("lateness halved", "LateHalf"),
                       ("lateness doubled", "LateDouble"), ("risk doubles, month 12", "Shift")):
        w = by[(wname, "weighted")]
        macros[f"RatioWeighted{key}"] = f"{w['ratio_all']:.2f}"
        macros[f"RatioLateWeighted{key}"] = f"{w['ratio_late']:.2f}"
        macros[f"SkillWeighted{key}"] = pct(w["skill"], 1)
        t = by[(wname, "tier only")]
        macros[f"RatioTierOnly{key}"] = f"{t['ratio_all']:.2f}"
    weighted = [r for r in rows if r["scoring"] == "weighted"]
    macros["RatioWeightedMin"] = f"{min(r['ratio_all'] for r in weighted):.2f}"
    macros["RatioWeightedMax"] = f"{max(r['ratio_all'] for r in weighted):.2f}"
    macros["MisspecSeeds"] = str(len(SEEDS))
    macros["MisspecHonest"] = str(CONFIG["n_honest"])
    with open(OUT / "misspecification_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(macros)


if __name__ == "__main__":
    main()
