#!/usr/bin/env python3
"""Scoring variants under misspecified worlds (Section 7, "Validation under misspecification").

Reuses analysis/issuer_policy of the contract repository. Three scoring rules are run on the same
borrower paths in five worlds, three seeds each:

  scoring  weighted    the policy as proposed (evidence weighted by recency, unsecured size and
                       time at risk; zero for interest-free and fully secured loans)
           unweighted  every repaid loan is one trial, good or bad, whatever it put at risk
           tier only   the tier's prior alone, no repayment evidence

  world    as assumed            the population the priors were fitted to; lateness at the ratio
                                 the policy assumes
           riskier population    within every tier, more of the population at the high PDs than
                                 the prior assumes
           lateness halved       late repayments at half the assumed ratio to defaults
           lateness doubled      at twice the assumed ratio
           risk doubles, mo. 12  every borrower's default and late probabilities double from
                                 month 12 (a regime shift the prior does not know)

Two evaluation samples, named for what they estimate:

  policy sample   the cycles each rule's own policy lent. Its Brier score is the policy score: the
                  accuracy of the predictions behind the loans that rule made. It mixes prediction
                  with selection, because the rule's lines decide who borrows (a borrower whose
                  available credit is below one USDC sits out the month) and a default ends the
                  borrower's record under that rule, so the three rules score different cycles.
  common panel    every (seed, borrower, month) in which the borrower would seek a loan (its
                  activity draw), scored on the outcome that loan would have had (its outcome
                  draw). Both draws are made by the world before any rule acts, so the panel is
                  the same for every rule and independent of the lending decision. Each rule's
                  prediction is its posterior for that borrower at that month, whether or not it
                  lent, including months in which it granted no line and months after a default
                  it observed. A default is not evidence under any rule (policy.loan_evidence and
                  the comparators count repaid loans only, and the contract ends the account), so
                  after a default the prediction is the prior plus whatever repayment evidence
                  survives the decay; the panel scores it as it stands. This scores the rule out
                  of its own sample: on the borrowers it declined and the months it did not lend.

Uncertainty: clusters are borrower paths, identified by (seed, borrower) and pooled across seeds
(SEEDS x n_honest clusters). Each world draws BOOT resamples of the clusters with replacement; the
same resample is used for every rule and both samples, so the aggregate Brier score, its skill
against the realised base rate and the paired differences between rules are bootstrapped on a
common footing. The interval covers borrower sampling only: the state the rules share within a
seed (the budget, the epochs, the farm) is not resampled.

Reported per (world, scoring): the pooled Brier score of the predicted cycle default probability
against the realised default with its 95% cluster-bootstrap interval, its skill against the
realised base rate, the ratio of realised to predicted defaults (all cycles, months 12 to 23, and
weighted by the line), the same Brier score and skill on the common panel, and (means over seeds)
the honest loss rate per exposure-year, the mean line of surviving borrowers at the last report and
the line that a bought identity running the recycled-seed farm holds at the end. Per world, the
paired difference of the Brier score (weighted minus unweighted, weighted minus tier only) on the
common panel and on the matched policy sample (the cycles both rules lent), with intervals.

Usage: python3 scripts/misspecification.py <path to microcredit-contract>     (a few minutes)

Writes data/misspecification.csv, data/misspecification_paired.csv, data/table_misspecification.tex,
data/table_misspecification_panel.tex, data/table_misspecification_lines.tex and
data/misspecification_summary.tex.
"""
import csv
import pathlib
import sys

import numpy as np

CONTRACT = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parents[3] / "microcredit-contract"
sys.path.insert(0, str(CONTRACT / "analysis/issuer_policy"))
import policy as pol  # noqa: E402
import simulate as sim  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/misspecification.py; do not edit.\n"
SEEDS = (0, 1, 2)
CONFIG = dict(n_honest=600, budget_lines=150.0, increase_lines=40.0, n_farm=2)
BOOT = 2000
ASSUMED_WEIGHTS = dict(pol.TIER_PD_WEIGHTS)
RISKIER_WEIGHTS = {
    "basic": (0.05, 0.15, 0.30, 0.25, 0.25),
    "standard": (0.10, 0.25, 0.30, 0.20, 0.15),
    "enhanced": (0.20, 0.35, 0.25, 0.12, 0.08),
}
POLICY = pol.PolicyParams()        # priors fitted to the assumed population and lateness
ORIGINAL_EVIDENCE = pol.evidence
ORIGINAL_PLAN = pol.plan_report


def unweighted(view, now, params):
    good = bad = 0.0
    for loan in view.loans:
        if loan.status != pol.LoanStatus.REPAID or loan.closed_at is None:
            continue
        if loan.closed_at > loan.due_at:
            bad += 1.0
        else:
            good += 1.0
    return good, bad


def tier_only(view, now, params):
    return 0.0, 0.0


SCORINGS = (("weighted", ORIGINAL_EVIDENCE), ("unweighted", unweighted), ("tier only", tier_only))
COMPARISONS = (("unweighted", "Unweighted"), ("tier only", "TierOnly"))


class ShiftedSimulation(sim.Simulation):
    """Every honest borrower's default and late probabilities double from month 12."""

    def _honest_borrow(self, h, at, m):
        if m < 12:
            return super()._honest_borrow(h, at, m)
        p_d, p_l = h.p_default, h.p_late
        h.p_default, h.p_late = min(1.0, 2 * p_d), min(1.0, 2 * p_l)
        try:
            return super()._honest_borrow(h, at, m)
        finally:
            h.p_default, h.p_late = p_d, p_l


def latent_default_probability(cls, h, m):
    """The world's default probability for a loan taken by `h` in month `m`."""
    if cls is ShiftedSimulation and m >= 12:
        return min(1.0, 2 * h.p_default)
    return h.p_default


WORLDS = (
    # name, weights of the population, world late ratio, simulation class
    ("as assumed", ASSUMED_WEIGHTS, 2.0, sim.Simulation),
    ("riskier population", RISKIER_WEIGHTS, 2.0, sim.Simulation),
    ("lateness halved", ASSUMED_WEIGHTS, 1.0, sim.Simulation),
    ("lateness doubled", ASSUMED_WEIGHTS, 4.0, sim.Simulation),
    ("risk doubles, month 12", ASSUMED_WEIGHTS, 2.0, ShiftedSimulation),
)


def run_one(weights, late_ratio, cls, scoring_fn, seed):
    """One simulation: the world draws its borrowers with `weights` and `late_ratio`; the policy
    keeps its own priors and its assumed ratio; the scoring rule is `scoring_fn`. Returns the
    result, the farm's line, and the rule's posterior cycle PD for every honest borrower at every
    month (shape months x n_honest), recorded at the plan step whether or not the rule lent."""
    pol.TIER_PD_WEIGHTS = weights
    world = pol.PolicyParams(late_ratio=late_ratio)
    try:
        s = cls(sim.SimConfig(seed=seed, params=world, **CONFIG))
    finally:
        pol.TIER_PD_WEIGHTS = ASSUMED_WEIGHTS
    s.p = POLICY                       # the issuer plans with the assumed priors and ratio
    index = {h.addr: i for i, h in enumerate(s.honest)}
    panel_pred = np.full((s.cfg.months, len(s.honest)), np.nan)
    month = [0]

    def plan_and_record(views, belief, params, now):
        views = list(views)
        for v in views:
            i = index.get(v.address)
            if i is not None and v.tier in params.tiers:
                panel_pred[month[0], i] = pol.pd_cycle(v, now, params)
        month[0] += 1
        return ORIGINAL_PLAN(views, belief, params, now)

    pol.evidence = scoring_fn
    pol.plan_report = plan_and_record
    try:
        res = s.run()
    finally:
        pol.evidence = ORIGINAL_EVIDENCE
        pol.plan_report = ORIGINAL_PLAN
    assert month[0] == s.cfg.months and not np.isnan(panel_pred).any()
    farm_line = s.provider.score(s.verified_farm) * POLICY.max_loan_usdc / pol.SCALE
    return res, farm_line, panel_pred


def samples(res, panel_pred, cls, seed):
    """The two evaluation samples of one run as (cluster, key, pred, y, weight) arrays, with the
    cluster id unique across seeds."""
    n = len(res.honest)
    c = np.array([(x[0], x[1], x[2], x[4]) for x in res.cycles], dtype=float)
    month, idx, pred, y = c[:, 0].astype(int), c[:, 1].astype(int), c[:, 2], c[:, 3]
    assert not np.isnan(pred).any()
    lines_at = res.lines[month, idx]
    policy = dict(cluster=seed * n + idx, key=seed * n * 100 + idx * 100 + month, month=month,
                  pred=pred, y=y, weight=np.maximum(lines_at, 0.0))
    active = np.array([h.active for h in res.honest]).T          # months x n
    outcome = np.array([h.outcome for h in res.honest]).T
    p_true = np.array([[latent_default_probability(cls, h, m) for h in res.honest]
                       for m in range(res.config.months)])
    m_idx, i_idx = np.nonzero(active < res.config.activity)
    panel = dict(cluster=seed * n + i_idx, key=seed * n * 100 + i_idx * 100 + m_idx, month=m_idx,
                 pred=panel_pred[m_idx, i_idx], y=(outcome[m_idx, i_idx] < p_true[m_idx, i_idx]).astype(float))
    return policy, panel


def concat(parts):
    return {k: np.concatenate([p[k] for p in parts]) for k in parts[0]}


def cluster_sums(cluster, values, n_clusters):
    return np.bincount(cluster, weights=values, minlength=n_clusters)


def brier_skill(sse, n, sy):
    """Brier score and skill against the realised base rate from pooled sums (vectorised over
    resamples)."""
    brier = sse / n
    base = sy / n
    brier_base = (sy * (1.0 - 2.0 * base) + n * base * base) / n      # mean of (base - y)^2, y in {0,1}
    with np.errstate(divide="ignore", invalid="ignore"):
        skill = np.where(brier_base > 0, 1.0 - brier / brier_base, 0.0)
    return brier, skill


def score(sample, n_clusters, boot_idx):
    """Pooled Brier score, skill and their 95% cluster-bootstrap intervals (resamples `boot_idx`)."""
    sse = cluster_sums(sample["cluster"], (sample["pred"] - sample["y"]) ** 2, n_clusters)
    n = cluster_sums(sample["cluster"], np.ones_like(sample["y"]), n_clusters)
    sy = cluster_sums(sample["cluster"], sample["y"], n_clusters)
    brier, skill = brier_skill(sse.sum(), n.sum(), sy.sum())
    b_boot, s_boot = brier_skill(sse[boot_idx].sum(axis=1), n[boot_idx].sum(axis=1), sy[boot_idx].sum(axis=1))
    return {
        "brier": float(brier), "brier_lo": float(np.quantile(b_boot, 0.025)), "brier_hi": float(np.quantile(b_boot, 0.975)),
        "skill": float(skill), "skill_lo": float(np.quantile(s_boot, 0.025)), "skill_hi": float(np.quantile(s_boot, 0.975)),
        "cycles": int(n.sum()), "defaults": int(sy.sum()),
    }


def paired(a, b, n_clusters, boot_idx):
    """Mean of (a's squared error - b's squared error) over the keys both samples contain, with its
    cluster-bootstrap interval on the same resamples."""
    keys, ia, ib = np.intersect1d(a["key"], b["key"], assume_unique=True, return_indices=True)
    assert np.array_equal(a["y"][ia], b["y"][ib]) and np.array_equal(a["cluster"][ia], b["cluster"][ib])
    d = (a["pred"][ia] - a["y"][ia]) ** 2 - (b["pred"][ib] - b["y"][ib]) ** 2
    sd = cluster_sums(a["cluster"][ia], d, n_clusters)
    n = cluster_sums(a["cluster"][ia], np.ones_like(d), n_clusters)
    boots = sd[boot_idx].sum(axis=1) / n[boot_idx].sum(axis=1)
    return {"delta": float(sd.sum() / n.sum()), "delta_lo": float(np.quantile(boots, 0.025)),
            "delta_hi": float(np.quantile(boots, 0.975)), "cycles": int(n.sum()), "clusters": int((n > 0).sum())}


def ratios(sample):
    month, pred, y, w = sample["month"], sample["pred"], sample["y"], sample["weight"]
    late = month >= 12
    return {
        "ratio_all": float(y.sum() / pred.sum()),
        "ratio_late": float(y[late].sum() / pred[late].sum()) if late.any() else float("nan"),
        "ratio_weighted": float((w * y).sum() / (w * pred).sum()) if w.sum() > 0 else float("nan"),
    }


def run_metrics(res, farm_line):
    months = [r for r in res.monthly if "exposure_usdc" in r]
    loss = sum(r["loss_honest_usdc"] for r in res.monthly)
    exposure_years = float(np.mean([r["exposure_usdc"] for r in months])) * res.config.months / 12
    alive = res.alive[-1]
    mean_line = float(res.lines[-1][alive].mean()) if alive.any() else float("nan")
    return {"loss_rate": loss / exposure_years if exposure_years > 0 else float("nan"),
            "mean_line_end": mean_line, "farm_line": farm_line}


def main():
    OUT.mkdir(exist_ok=True)
    rng = np.random.default_rng(np.random.SeedSequence([sim.BASE_SEED, 99]))
    n_clusters = len(SEEDS) * CONFIG["n_honest"]
    rows, paired_rows = [], []
    for wname, weights, late_ratio, cls in WORLDS:
        boot_idx = rng.integers(0, n_clusters, size=(BOOT, n_clusters))   # one design per world
        pooled = {}
        for sname, fn in SCORINGS:
            per_run, pol_parts, panel_parts = [], [], []
            for seed in SEEDS:
                res, farm_line, panel_pred = run_one(weights, late_ratio, cls, fn, seed)
                per_run.append(run_metrics(res, farm_line))
                p, q = samples(res, panel_pred, cls, seed)
                pol_parts.append(p)
                panel_parts.append(q)
            policy, panel = concat(pol_parts), concat(panel_parts)
            pooled[sname] = (policy, panel)
            row = {"world": wname, "scoring": sname, "seeds": len(SEEDS)}
            row.update(score(policy, n_clusters, boot_idx))
            row.update(ratios(policy))
            row.update({f"panel_{k}": v for k, v in score(panel, n_clusters, boot_idx).items()})
            row.update({k: float(np.mean([r[k] for r in per_run])) for k in per_run[0]})
            rows.append(row)
            print(wname, sname, {k: (round(v, 6) if isinstance(v, float) else v) for k, v in row.items()})
        for other, _ in COMPARISONS:
            for sample_name, j in (("common panel", 1), ("matched policy sample", 0)):
                r = paired(pooled["weighted"][j], pooled[other][j], n_clusters, boot_idx)
                paired_rows.append({"world": wname, "comparison": f"weighted minus {other}", "sample": sample_name, **r})
                print(wname, other, sample_name, r)
    with open(OUT / "misspecification.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    with open(OUT / "misspecification_paired.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(paired_rows[0]))
        w.writeheader()
        w.writerows(paired_rows)

    def pct(x, d=2):
        return f"{100 * x:.{d}f}"

    def ci(r, k, d):
        return f"{pct(r[k], d)} [{pct(r[k + '_lo'], d)}, {pct(r[k + '_hi'], d)}]"

    lines = [f"{r['world']} & {r['scoring']} & {r['cycles']} & {ci(r, 'brier', 4)} & {pct(r['skill'])}\\% & "
             f"{r['ratio_all']:.2f} & {r['ratio_late']:.2f} & {r['ratio_weighted']:.2f} \\\\" for r in rows]
    with open(OUT / "table_misspecification.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")

    def micro(r):
        return f"{1e6 * r['delta']:.2f} [{1e6 * r['delta_lo']:.2f}, {1e6 * r['delta_hi']:.2f}]"

    by_pair = {(r["world"], r["comparison"], r["sample"]): r for r in paired_rows}
    lines = []
    for r in rows:
        delta = "" if r["scoring"] == "weighted" else micro(by_pair[(r["world"], f"weighted minus {r['scoring']}", "common panel")])
        lines.append(f"{r['world']} & {r['scoring']} & {ci(r, 'panel_brier', 4)} & {pct(r['panel_skill'])}\\% & {delta} \\\\")
    with open(OUT / "table_misspecification_panel.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")
    lines = [f"{r['world']} & {r['scoring']} & {pct(r['loss_rate'])}\\% & {r['mean_line_end']:.1f} & {r['farm_line']:.2f} \\\\"
             for r in rows]
    with open(OUT / "table_misspecification_lines.tex", "w") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")

    by = {(r["world"], r["scoring"]): r for r in rows}
    macros = {}
    for sname, key in (("weighted", "Weighted"), ("unweighted", "Unweighted"), ("tier only", "TierOnly")):
        a = by[("as assumed", sname)]
        macros[f"Brier{key}Assumed"] = pct(a["brier"], 4)
        macros[f"BrierLo{key}Assumed"] = pct(a["brier_lo"], 4)
        macros[f"BrierHi{key}Assumed"] = pct(a["brier_hi"], 4)
        macros[f"Skill{key}Assumed"] = pct(a["skill"])
        macros[f"Cycles{key}Assumed"] = f"{a['cycles']:,}"
        macros[f"PanelBrier{key}Assumed"] = pct(a["panel_brier"], 4)
        macros[f"PanelSkill{key}Assumed"] = pct(a["panel_skill"])
        macros[f"PanelSkillLo{key}Assumed"] = pct(a["panel_skill_lo"])
        macros[f"PanelSkillHi{key}Assumed"] = pct(a["panel_skill_hi"])
        macros[f"Ratio{key}Assumed"] = f"{a['ratio_all']:.2f}"
        macros[f"FarmLine{key}"] = f"{a['farm_line']:.2f}"
        macros[f"MeanLine{key}Assumed"] = f"{a['mean_line_end']:.1f}"
    for other, key in COMPARISONS:
        for sample_name, skey in (("common panel", "Panel"), ("matched policy sample", "Matched")):
            r = by_pair[("as assumed", f"weighted minus {other}", sample_name)]
            macros[f"{skey}Delta{key}Assumed"] = f"{1e6 * r['delta']:.2f}"
            macros[f"{skey}DeltaLo{key}Assumed"] = f"{1e6 * r['delta_lo']:.2f}"
            macros[f"{skey}DeltaHi{key}Assumed"] = f"{1e6 * r['delta_hi']:.2f}"
            macros[f"{skey}Cycles{key}Assumed"] = f"{r['cycles']:,}"
    macros["PanelCyclesAssumed"] = f"{by[('as assumed', 'weighted')]['panel_cycles']:,}"
    for wname, key in (("riskier population", "Riskier"), ("lateness halved", "LateHalf"),
                       ("lateness doubled", "LateDouble"), ("risk doubles, month 12", "Shift")):
        w = by[(wname, "weighted")]
        macros[f"RatioWeighted{key}"] = f"{w['ratio_all']:.2f}"
        macros[f"RatioLateWeighted{key}"] = f"{w['ratio_late']:.2f}"
        macros[f"SkillWeighted{key}"] = pct(w["skill"])
        macros[f"PanelSkillWeighted{key}"] = pct(w["panel_skill"])
        t = by[(wname, "tier only")]
        macros[f"RatioTierOnly{key}"] = f"{t['ratio_all']:.2f}"
    a = by_pair[("as assumed", "weighted minus tier only", "common panel")]
    macros["PanelGainTierOnlyAssumed"] = f"{round(by[('as assumed', 'weighted')]['panel_brier'] / abs(a['delta']), -2):,.0f}"
    panel = {other: [r for r in paired_rows if r["sample"] == "common panel" and r["comparison"] == f"weighted minus {other}"]
             for other, _ in COMPARISONS}
    macros["PanelBetterThanTierOnly"] = str(sum(1 for r in panel["tier only"] if r["delta_hi"] < 0))
    macros["PanelTiedWithUnweighted"] = str(sum(1 for r in panel["unweighted"] if r["delta_lo"] <= 0 <= r["delta_hi"]))
    macros["PanelWeightedBeatsUnweighted"] = str(sum(1 for r in panel["unweighted"] if r["delta_hi"] < 0))
    macros["MisspecWorlds"] = str(len(WORLDS))
    weighted = [r for r in rows if r["scoring"] == "weighted"]
    macros["RatioWeightedMin"] = f"{min(r['ratio_all'] for r in weighted):.2f}"
    macros["RatioWeightedMax"] = f"{max(r['ratio_all'] for r in weighted):.2f}"
    macros["MisspecSeeds"] = str(len(SEEDS))
    macros["MisspecHonest"] = str(CONFIG["n_honest"])
    macros["MisspecClusters"] = f"{n_clusters:,}"
    macros["MisspecBoot"] = f"{BOOT:,}"
    with open(OUT / "misspecification_summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(macros)


if __name__ == "__main__":
    main()
