#!/usr/bin/env python3
"""Every table, curve and number of the paper "Pricing the Reserve" (lending-equilibrium).

The pool, the loss model and the reserve recursion are those of the pricing-and-reserve paper
(one-factor Vasicek losses from analysis/credit_risk of the contract repository, re-lent after
write-offs, cash-basis interest, a reserve that is never released). On top of them this script
computes:

  A. the loan-rate identity and the lenders' floor, by reserve share        (Section 4.1)
  B. lenders' long-run return, guaranteed return and earned credit            (Section 4.2)
  C. lenders' risk of losing principal against reserve share and seed capital, finite pools,
     and seed capital against share over a common horizon                     (Section 5)
  D. the market equilibrium: rate, volume and the volume-maximising share, under the long-run
     participation rule and under a common holding period; plateau sensitivity (Section 6)
  E. liquidity: time to exit and the utilisation a liquidity target allows    (Section 7)
  F. the adverse-selection threshold                                           (Section 8)

Usage: python3 scripts/equilibrium.py <path to microcredit-contract>      (about 6 minutes)

Writes data/*.csv (curves), data/*.tex (table rows and the macros of summary.tex). Every draw uses
a fixed seed, so two runs give byte-identical files.
"""
import csv
import os
import pathlib
import sys

import numpy as np
from scipy.optimize import brentq

CONTRACT = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parents[3] / "microcredit-contract"
sys.path.insert(0, str(CONTRACT / "analysis/credit_risk"))
import vasicek as vs  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent / "data"
OUT = ROOT / os.environ["OUTSUB"] if os.environ.get("OUTSUB") else ROOT
HEADER = "% Generated by scripts/equilibrium.py; do not edit.\n"

SEED = 20261005
U = 0.85            # utilisation of deposits (the contract caps it at 90%)
F = 0.0             # protocol fee share of interest
E = vs.EFFR         # funding rate, 4.33%
PD = float(os.environ.get("PD", "0.05"))              # annual probability of default of the book
PREMIUM = float(os.environ.get("PREMIUM", "0.08"))    # risk premium over the funding rate (800 bps at PD 5%)
PRIME = 0.075       # WSJ prime when EFFR was 4.33% (December 2024 to September 2025): an external input
A_REF = E + PREMIUM  # the production loan rate, 12.33%
TERM_DAYS = 30.0    # loan term
H = 10              # horizon of the safety criterion, years
N_SAFE = 200_000    # paths for the safety tables
N_GRID = 100_000    # paths for the equilibrium grids
RHO = vs.basel_other_retail_correlation(PD)
EL = float(vs.replenished_expected_loss(PD, RHO))   # expected loss per exposure-year, re-lent
R_C = EL / A_REF                                   # reserve share whose inflow equals expected loss

macros = {}


def pct(x, d=2):
    return f"{100 * float(x):.{d}f}"


def put(name, value):
    macros[name] = value


def write_csv(name, rows):
    with open(OUT / name, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)


def write_tex(name, lines):
    with open(OUT / name, "w") as fh:
        fh.write(HEADER)
        for line in lines:
            fh.write(line + "\n")


def losses(years, n, tag):
    """Annual loss rates per unit lent, shape (years, n), common to every parameter setting."""
    rng = np.random.default_rng(np.random.SeedSequence([SEED, tag]))
    out = np.empty((years, n))
    for t in range(years):
        p = vs.conditional_pd(PD, RHO, rng.standard_normal(n))
        out[t] = np.asarray(vs.replenished_default_rate(np.clip(p, 0.0, 1 - 1e-12)))
    return out


def lender_paths(lm, r, a, k, years):
    """Lenders' annual returns Y (years, n) per unit of deposits, and the reserve R after each year.

    The reserve starts at k (external seed, per unit of deposits), gains u*a*r a year, and pays
    u*L_t first; lenders bear the rest. Y_t = u a (1-f-r) - lenders' loss.
    """
    n = lm.shape[1]
    reserve = np.full(n, float(k))
    y = np.empty((years, n))
    res = np.empty((years, n))
    for t in range(years):
        loss = U * lm[t]
        avail = reserve + U * a * r
        lender_loss = np.maximum(loss - avail, 0.0)
        reserve = np.maximum(avail - loss, 0.0)
        y[t] = U * a * (1 - F - r) - lender_loss
        res[t] = reserve
    return y, res


def p_principal_loss(lm, r, a, k, years):
    """P(lenders' return is negative in some year <= years). Equal to P(u L_t > u a (1-f) + R_{t-1})."""
    reserve = np.full(lm.shape[1], float(k))
    hit = np.zeros(lm.shape[1], dtype=bool)
    for t in range(years):
        loss = U * lm[t]
        hit |= loss > U * a * (1 - F) + reserve
        reserve = np.maximum(reserve + U * a * r - loss, 0.0)
    return float(hit.mean())


def long_run_yield(a, r):
    """Lenders' long-run expected return per unit of deposits under the lock (pricing paper, Theorem 2)."""
    return U * (a * (1 - F) - max(EL, a * r))


# ------------------------------------------------------------------------------------------------
# A. The rate identity and the lenders' floor
# ------------------------------------------------------------------------------------------------
def a_min(r, h):
    """Lowest APR at which lenders earn e + h in the long run (Proposition 1)."""
    free = ((E + h) / U + EL) / (1 - F)              # while the reserve share is free
    locked = (E + h) / (U * (1 - F - r))              # once a*r exceeds expected loss
    return max(free, locked)


def section_a():
    put("Effr", pct(E))
    put("ARef", pct(A_REF))
    put("ELre", pct(EL))
    put("UBase", f"{100 * U:.0f}")
    put("PrimeIllus", pct(PRIME))
    put("RC", pct(R_C, 1))
    put("PremBps", f"{PREMIUM * 1e4:.0f}")
    for h, tag in ((0.0, "Zero"), (0.01, "One"), (0.02, "Two")):
        a0 = ((E + h) / U + EL) / (1 - F)
        put(f"AFree{tag}", pct(a0))
        put(f"RBar{tag}", pct(EL / a0, 1))
    put("IdleDrag", pct(E * (1 / U - 1)))
    put("MarginRoom", pct(A_REF - (E / U + EL)))
    put("RMaxLenders", pct(1 - F - E / (U * A_REF), 1))
    grid = np.round(np.arange(0.0, 0.7001, 0.0125), 4)
    write_csv("floor_curve.csv", [
        {"r": float(r), "h0": 100 * a_min(r, 0.0), "h1": 100 * a_min(r, 0.01), "h2": 100 * a_min(r, 0.02)}
        for r in grid
    ])
    # Decomposition of the production APR by reserve share: a(1-f) = e/u + x/u + max(EL, a r).
    lines = []
    for r in (0.30, R_C, 0.45, 0.50, 0.55, 0.60, 0.65):
        reserve_term = max(EL, A_REF * r)
        margin_per_lent = A_REF * (1 - F) - E / U - reserve_term      # x / u
        x = U * margin_per_lent                                      # lenders' margin over e
        label = f"{100 * r:.1f}"
        lines.append(
            f"{label} & {pct(E)} & {pct(E * (1 / U - 1))} & {pct(margin_per_lent)} & {pct(reserve_term)} & "
            f"{pct(max(0.0, reserve_term - EL))} & {pct(E + x)} \\\\"
        )
        if abs(r - 0.45) < 1e-9:
            put("MarginAtFortyFive", pct(margin_per_lent))
            put("LenderMarginFortyFive", pct(x))
            put("ReserveTermFortyFive", pct(reserve_term))
            put("ReserveSurplusFortyFive", pct(reserve_term - EL))
        if abs(r - 0.65) < 1e-9:
            put("MarginAtSixtyFive", pct(margin_per_lent))
            put("LenderMarginSixtyFive", pct(x))
    write_tex("table_decomposition.tex", lines)
    # The floor by lenders' required margin h and reserve share.
    lines = []
    for r in (0.30, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70):
        lines.append(
            f"{100 * r:.0f} & {pct(a_min(r, 0.0))} & {pct(a_min(r, 0.01))} & {pct(a_min(r, 0.02))} \\\\"
        )
    write_tex("table_floor.tex", lines)


# ------------------------------------------------------------------------------------------------
# B. Lenders' return and borrowers' earned credit at the production APR
# ------------------------------------------------------------------------------------------------
def section_b():
    lines = []
    for r in (0.30, R_C, 0.45, 0.50, 0.55, 0.60, 0.65):
        y = long_run_yield(A_REF, r)
        guaranteed = U * A_REF * (1 - F - r)
        g = r * A_REF
        lines.append(
            f"{100 * r:.1f} & {pct(y)} & {pct(guaranteed)} & {pct(y - E)} & {pct(g)} & "
            f"{np.log(2) / g:.1f} & {1 / r:.2f} \\\\"
        )
        tag = {0.45: "FortyFive", 0.65: "SixtyFive"}.get(round(r, 2))
        if abs(r - R_C) < 1e-12:
            put("LRAtRC", pct(y))
        if tag:
            put(f"LRAt{tag}", pct(y))
            put(f"GuarAt{tag}", pct(guaranteed))
            put(f"GrowthAt{tag}", pct(g))
            put(f"DoubleAt{tag}", f"{np.log(2) / g:.1f}")
            put(f"PriceCreditAt{tag}", f"{1 / r:.2f}")
    write_tex("table_lender.tex", lines)
    put("GrowthGain", f"{100 * (0.65 - 0.45) * A_REF:.1f}")
    # Slope of lenders' long-run return in the reserve share above R_C: u * a per unit.
    put("SlopePerPoint", pct(U * A_REF / 100))
    # Growth of earned credit: the exponential is the continuous-payment approximation; with
    # repayment and redrawing every term, the factor over a year is (1 + r a T/365)^(365/T).
    m = 365.0 / TERM_DAYS
    for r, tag in ((0.45, "FortyFive"), (0.65, "SixtyFive")):
        g = r * A_REF
        put(f"GrowthCont{tag}", pct(np.exp(g) - 1))
        put(f"GrowthDisc{tag}", pct((1 + g / m) ** m - 1))
    put("TermsPerYear", f"{m:.2f}")


# ------------------------------------------------------------------------------------------------
# C. Lenders' risk of losing principal; seed capital against reserve share
# ------------------------------------------------------------------------------------------------
def section_c():
    lm = losses(H, N_SAFE, tag=11)
    grid = np.round(np.arange(0.0, 0.7001, 0.0125), 4)
    seeds = (0.0, 0.02, 0.05)
    rows = []
    check_err = 0.0
    mv = {}
    for r in grid:
        row = {"r": float(r)}
        for k in seeds:
            y, res = lender_paths(lm, r, A_REF, k, H)
            avg = y.mean(axis=0)
            p_neg = float((y.min(axis=0) < 0).mean())
            p_evt = p_principal_loss(lm, r, A_REF, k, H)
            assert abs(p_neg - p_evt) < 1e-12, (r, k, p_neg, p_evt)
            # Theorem 1 of the pricing paper with an external seed: sum Y = H u a (1-f) - sum u L - (R_H - k)
            lhs = y.sum(axis=0)
            rhs = H * U * A_REF * (1 - F) - (U * lm).sum(axis=0) - (res[-1] - k)
            check_err = max(check_err, float(np.max(np.abs(lhs - rhs))))
            tag = f"k{int(round(k * 100))}"
            row[f"p_{tag}"] = 100 * p_neg
            row[f"mean_{tag}"] = 100 * float(avg.mean())
            row[f"res_{tag}"] = 100 * float(res[-1].mean())
            if k == 0.0 and abs(r - 0.45) < 1e-9:
                for lam in (5, 20, 100):
                    mv[lam] = float(avg.mean() - lam / 2 * avg.var())
                put("MVVarFortyFive", f"{avg.var() * 1e4:.2f}")
        rows.append(row)
    assert check_err < 1e-9, check_err
    mant, expo = f"{check_err:.0e}".split("e")
    put("IdentityErr", f"{mant}\\times10^{{{int(expo)}}}")
    write_csv("safety_curve.csv", rows)
    by_r = {round(r["r"], 4): r for r in rows}

    def p_at(r, k):
        """Interpolated principal-loss probability on a fine r grid."""
        key = f"p_k{int(round(k * 100))}"
        xs = np.array([x["r"] for x in rows])
        ys = np.array([x[key] for x in rows])
        return float(np.interp(r, xs, ys)) / 100

    put("PTenAtRC", pct(p_at(R_C, 0.0), 1))
    put("PTenAtFortyFive", pct(p_at(0.45, 0.0), 1))
    put("PTenAtFifty", pct(p_at(0.50, 0.0), 1))
    put("PTenAtFiftyFive", pct(p_at(0.55, 0.0), 1))
    put("PTenAtSixtyFive", pct(p_at(0.65, 0.0), 1))
    put("PTenAtFortyFiveSeedTwo", pct(p_at(0.45, 0.02), 1))
    put("PTenAtFortyFiveSeedFive", pct(p_at(0.45, 0.05), 1))
    put("PTenAtRCSeedFive", pct(p_at(R_C, 0.05), 1))
    put("MeanFortyFive", f"{by_r[0.45]['mean_k0']:.2f}")
    put("MeanZero", f"{by_r[0.0]['mean_k0']:.2f}")
    put("ResTenRC", f"{np.interp(R_C, [x['r'] for x in rows], [x['res_k0'] for x in rows]):.1f}")
    put("MeanRC", f"{np.interp(R_C, [x['r'] for x in rows], [x['mean_k0'] for x in rows]):.2f}")
    put("ResTenFortyFive", f"{by_r[0.45]['res_k0']:.1f}")
    put("ResTenSixtyFive", f"{by_r[0.65]['res_k0']:.1f}")
    # Mean-variance penalty at r = 45%: negligible against the cost of the reserve.
    base = float(np.interp(0.45, [x['r'] for x in rows], [x['mean_k0'] for x in rows])) / 100
    for lam, name in ((5, "Five"), (20, "Twenty"), (100, "Hundred")):
        put(f"MVPen{name}", f"{1e4 * (base - mv[lam]):.1f}")

    lines = []
    for r in (0.30, R_C, 0.45, 0.50, 0.55, 0.60, 0.65):
        mean0 = float(np.interp(r, [x["r"] for x in rows], [x["mean_k0"] for x in rows]))
        res0 = float(np.interp(r, [x["r"] for x in rows], [x["res_k0"] for x in rows]))
        lines.append(
            f"{100 * r:.1f} & {pct(p_at(r, 0.0), 1)} & {pct(p_at(r, 0.02), 1)} & {pct(p_at(r, 0.05), 1)} & "
            f"{mean0:.2f} & {res0:.1f} \\\\"
        )
    write_tex("table_safety.tex", lines)

    # r_safe: smallest share on a fine grid with P <= alpha, by seed.
    fine = np.round(np.arange(0.0, 0.7001, 0.0025), 4)
    lines = []
    for alpha in (0.10, 0.05, 0.02):
        cells = []
        for k in seeds:
            hit = None
            for r in fine:
                if p_at(r, k) <= alpha:
                    hit = r
                    break
            cells.append("--" if hit is None else f"{100 * hit:.1f}")
        lines.append(f"{100 * alpha:.0f} & " + " & ".join(cells) + " \\\\")
    write_tex("table_rsafe.tex", lines)

    # Finite pools: with n loans the realised annual loss rate is a binomial count around the
    # conditional rate (the base case is the infinitely granular pool).
    rng = np.random.default_rng(np.random.SeedSequence([SEED, 13]))
    finite = {}
    for n_loans in (100, 1000):
        lmf = rng.binomial(n_loans, np.clip(lm, 0.0, 1.0)) / n_loans
        finite[n_loans] = {r: p_principal_loss(lmf, r, A_REF, 0.0, H) for r in (R_C, 0.45, 0.55, 0.65)}
    lines = []
    for r in (R_C, 0.45, 0.55, 0.65):
        lines.append(f"{100 * r:.1f} & {pct(finite[100][r], 1)} & {pct(finite[1000][r], 1)} & {pct(p_at(r, 0.0), 1)} \\\\")
    write_tex("table_finite_pool.tex", lines)
    put("PTenFortyFivePoolHundred", pct(finite[100][0.45], 1))
    put("PTenFortyFivePoolThousand", pct(finite[1000][0.45], 1))
    put("PTenRCPoolHundred", pct(finite[100][R_C], 1))

    # Seed against share: the seed that gives, at the free share R_C, the protection of a higher
    # share. Costs are compared over the same horizon H: the share costs lenders the difference in
    # mean return over the first H years (and u a (r - R_C) a year in the long run); the seed is a
    # gift that its funder never recovers, so its cost is the annuity that repays it at the hurdle
    # rate over H years.
    # Both costs are levelised with the same discount factors: the seed as the annuity that repays
    # it over H years at the hurdle h, k / A(h), and the share as the discounted sum of the yearly
    # differences in expected return divided by the same A(h), where A(h) = sum_t (1+h)^-t.
    disc = {E: (1 + E) ** -np.arange(1, H + 1), 0.15: 1.15 ** -np.arange(1, H + 1)}
    ann = {h: 1.0 / disc[h].sum() for h in disc}
    put("AnnuityAtE", f"{ann[E]:.3f}")
    put("AnnuityAtFifteen", f"{ann[0.15]:.3f}")
    path_rc = lender_paths(lm, R_C, A_REF, 0.0, H)[0].mean(axis=1)   # expected return by year at R_C
    lines = []
    for r in (0.45, 0.50, 0.55, 0.60, 0.65):
        target = p_at(r, 0.0)
        found = None
        for k in np.arange(0.0, 0.2001, 0.0025):
            lm_k = p_principal_loss(lm, R_C, A_REF, float(k), H)
            if lm_k <= target + 1e-12:
                found = float(k)
                break
        share_cost = U * A_REF * (r - R_C)            # yearly, per unit of deposits, lenders' yield forgone
        delta = path_rc - lender_paths(lm, r, A_REF, 0.0, H)[0].mean(axis=1)   # yearly cost over the first H years
        share_ten = {h: float(delta @ disc[h] / disc[h].sum()) for h in disc}  # levelised at the hurdle
        seed_cost = {h: (None if found is None else found * ann[h]) for h in disc}
        lines.append(
            f"{100 * r:.0f} & {pct(target, 1)} & " +
            ("--" if found is None else f"{100 * found:.2f}") + " & " + pct(share_cost) + " & " +
            pct(share_ten[E]) + " & " + pct(share_ten[0.15]) + " & " +
            ("--" if found is None else pct(seed_cost[E])) + " & " +
            ("--" if found is None else pct(seed_cost[0.15])) + " \\\\"
        )
        tag = {0.45: "FortyFive", 0.55: "FiftyFive"}.get(round(r, 2))
        if tag and found is not None:
            put(f"SeedEquiv{tag}", f"{100 * found:.2f}")
            put(f"SeedCost{tag}", pct(seed_cost[0.15]))
            put(f"SeedCostE{tag}", pct(seed_cost[E]))
            put(f"ShareCost{tag}", pct(share_cost))
            put(f"ShareCostTen{tag}", pct(float(delta.mean())))
            put(f"ShareCostTenE{tag}", pct(share_ten[E]))
            put(f"ShareCostTenH{tag}", pct(share_ten[0.15]))
    write_tex("table_seed.tex", lines)
    # Late repayment (Section 7): cash collected by the end of one term when a fraction of the
    # book pays late, per unit of deposits.
    put("LateShare", "10")
    put("LateCollectedByTerm", f"{1 - U + 0.9 * U:.3f}")
    put("LateRemaining", f"{0.1 * U:.3f}")
    return lm


# ------------------------------------------------------------------------------------------------
# D. The market equilibrium
# ------------------------------------------------------------------------------------------------
R_GRID = np.round(np.arange(0.0, 0.7001, 0.0125), 4)
A_GRID = np.round(A_REF + np.arange(-0.03, 0.1501, 0.005), 4)
R_GRID_FINE = np.round(np.arange(0.0, 0.7001, 0.00625), 5)
A_GRID_FINE = np.round(A_REF + np.arange(-0.03, 0.1501, 0.0025), 5)


def safety_grid(lm, k, years=H, rg=R_GRID, ag=A_GRID):
    """P(lenders lose principal within `years`) on the (reserve share, APR) grid, seed k."""
    return np.array([[p_principal_loss(lm, r, a, k, years) for a in ag] for r in rg])


def yield_grid(lm, k, years=H, rg=R_GRID, ag=A_GRID):
    """Expected average annual return over `years` of a lender who deposits at launch, seed k."""
    return np.array([[float(lender_paths(lm, r, a, k, years)[0].mean()) for a in ag] for r in rg])


def interp_p(grid, r, a, rg=R_GRID, ag=A_GRID):
    i = min(max(int(np.searchsorted(rg, r)), 1), len(rg) - 1)
    j = min(max(int(np.searchsorted(ag, a)), 1), len(ag) - 1)
    wr = (r - rg[i - 1]) / (rg[i] - rg[i - 1])
    wa = (a - ag[j - 1]) / (ag[j] - ag[j - 1])
    return ((1 - wr) * ((1 - wa) * grid[i - 1, j - 1] + wa * grid[i - 1, j])
            + wr * ((1 - wa) * grid[i, j - 1] + wa * grid[i, j]))


class Market:
    """Heterogeneous lenders, constant-elasticity borrowers, calibrated so that the production APR
    clears the market at the free reserve share R_C with no seed.

    Lenders' yield is the long-run return (ygrid None: the hybrid rule of the first version) or
    the expected average return over a common holding period (ygrid from yield_grid)."""

    def __init__(self, grid0, eta, tau, abar, ygrid0=None, rg=R_GRID, ag=A_GRID):
        self.eta, self.tau, self.abar = eta, tau, abar
        self.rg, self.ag = rg, ag
        c_ref = self.yld(A_REF, R_C, ygrid0)
        p_ref = interp_p(grid0, R_C, A_REF, rg, ag)
        self.w_hat = 1.0 / (U * self._share(c_ref, p_ref))   # u * deposits = 1 at the reference

    def _share(self, c, p):
        x = c - E
        g = 0.0 if x <= 0 else 1.0 - np.exp(-x / self.tau)
        return g * (1.0 if self.abar is None else np.exp(-p / self.abar))

    def yld(self, a, r, ygrid):
        return long_run_yield(a, r) if ygrid is None else interp_p(ygrid, r, a, self.rg, self.ag)

    def supply(self, a, r, grid, ygrid=None):
        """Loans that lenders fund at APR a, reserve share r (u times deposits)."""
        return U * self.w_hat * self._share(self.yld(a, r, ygrid), interp_p(grid, r, a, self.rg, self.ag))

    def demand(self, a):
        return (a / A_REF) ** (-self.eta)

    def solve(self, r, grid, ygrid=None):
        def excess(a):
            return self.supply(a, r, grid, ygrid) - self.demand(a)
        lo, hi = float(self.ag[0]), float(self.ag[-1])
        if excess(hi) < 0:
            return float("nan"), float("nan")
        if excess(lo) >= 0:
            return lo, self.demand(lo)
        a = brentq(excess, lo, hi, xtol=1e-10)
        return a, self.demand(a)


def summarise(pts, fine):
    """Curves and the summary (volume-maximising share, plateau, volumes) of one scenario."""
    a_s = np.array([p[0] for p in pts])
    v_s = np.array([p[1] for p in pts])
    ok = ~np.isnan(v_s)
    best = int(np.nanargmax(v_s))
    vmax = float(v_s[best])
    near = fine[ok & (v_s >= 0.99 * vmax)]
    at = lambda r: float(v_s[int(np.argmin(np.abs(fine - r)))])  # noqa: E731
    return a_s, v_s, {
        "rhat": float(fine[best]), "vmax": vmax, "lo99": float(near.min()), "hi99": float(near.max()),
        "v0": at(0.0), "vrc": at(R_C), "v45": at(0.45), "v50": at(0.50), "v55": at(0.55), "v65": at(0.65),
        "a45": float(a_s[int(np.argmin(np.abs(fine - 0.45)))]),
        "a65": float(a_s[int(np.argmin(np.abs(fine - 0.65)))]),
    }


def section_d(lm_safe):
    lm = lm_safe[:, :N_GRID]
    grids = {k: safety_grid(lm, k) for k in (0.0, 0.02, 0.05)}
    scenarios = [
        # name, eta, tau, abar, k, label
        ("yield", 1.0, 0.01, None, 0.0),
        ("base", 1.0, 0.01, 0.10, 0.0),
        ("base_k2", 1.0, 0.01, 0.10, 0.02),
        ("base_k5", 1.0, 0.01, 0.10, 0.05),
        ("abar5", 1.0, 0.01, 0.05, 0.0),
        ("abar20", 1.0, 0.01, 0.20, 0.0),
        ("tau05", 1.0, 0.005, 0.10, 0.0),
        ("tau2", 1.0, 0.02, 0.10, 0.0),
        ("eta05", 0.5, 0.01, 0.10, 0.0),
        ("eta2", 2.0, 0.01, 0.10, 0.0),
    ]
    fine = np.round(np.arange(0.0, 0.7001, 0.0025), 4)
    curves = {}
    summary = []
    for name, eta, tau, abar, k in scenarios:
        mk = Market(grids[0.0], eta, tau, abar)
        pts = [mk.solve(r, grids[k]) for r in fine]
        a_s, v_s, s = summarise(pts, fine)
        curves[name] = (a_s, v_s)
        summary.append({"name": name, "eta": eta, "tau": tau, "abar": abar, "k": k, **s})
    write_csv("equilibrium_curves.csv", [
        {"r": float(r), **{f"a_{n}": 100 * float(curves[n][0][i]) for n in curves},
         **{f"v_{n}": float(curves[n][1][i]) for n in curves}}
        for i, r in enumerate(fine)
    ])
    write_csv("equilibrium_summary.csv", summary)
    by = {s["name"]: s for s in summary}

    def lab(s):
        abar = "$\\infty$" if s["abar"] is None else f"{100 * s['abar']:.0f}"
        return f"{s['eta']:g} & {100 * s['tau']:.1f} & {abar} & {100 * s['k']:.0f}"

    lines = []
    for name in ("yield", "base", "abar5", "abar20", "tau05", "tau2", "eta05", "eta2", "base_k2", "base_k5"):
        s = by[name]
        rhat = f"$\\le {100 * R_C:.1f}$" if name == "yield" else f"{100 * s['rhat']:.1f}"
        lines.append(
            f"{lab(s)} & {rhat} & {s['vmax']:.3f} & "
            f"{100 * s['lo99']:.1f}--{100 * s['hi99']:.1f} & {s['v45']:.3f} & {s['v55']:.3f} & {s['v65']:.3f} \\\\"
        )
    write_tex("table_equilibrium.tex", lines)
    mk_y = Market(grids[0.0], 1.0, 0.01, None)
    mk_b = Market(grids[0.0], 1.0, 0.01, 0.10)
    lines = []
    fixed = {}
    for r in (R_C, 0.45, 0.50, 0.55, 0.60, 0.65):
        i = int(np.argmin(np.abs(fine - r)))
        # premium unchanged: volume is the short side, min(supply, demand) at the production APR
        vf_y = min(mk_y.supply(A_REF, r, grids[0.0]), mk_y.demand(A_REF))
        vf_b = min(mk_b.supply(A_REF, r, grids[0.0]), mk_b.demand(A_REF))
        fixed[round(r, 4)] = (vf_y, vf_b)
        lines.append(
            f"{100 * r:.1f} & {100 * curves['yield'][0][i]:.2f} & {curves['yield'][1][i]:.3f} & {vf_y:.3f} & "
            f"{100 * curves['base'][0][i]:.2f} & {curves['base'][1][i]:.3f} & {vf_b:.3f} \\\\"
        )
    write_tex("table_eq_curve.tex", lines)
    put("VFixedFortyFiveYield", f"{fixed[0.45][0]:.3f}")
    put("VFixedFortyFiveBase", f"{fixed[0.45][1]:.3f}")
    put("VFixedSixtyFiveYield", f"{fixed[0.65][0]:.3f}")
    put("VFixedSixtyFiveBase", f"{fixed[0.65][1]:.3f}")
    b = by["base"]
    put("RHatBase", f"{100 * b['rhat']:.1f}")
    put("VMaxBase", f"{b['vmax']:.3f}")
    put("VFortyFiveBase", f"{b['v45']:.3f}")
    put("VSixtyFiveBase", f"{b['v65']:.3f}")
    put("AFortyFiveBase", pct(b["a45"]))
    put("ASixtyFiveBase", pct(b["a65"]))
    y = by["yield"]
    put("VFortyFiveYield", f"{y['v45']:.3f}")
    put("VFiftyYield", f"{y['v50']:.3f}")
    put("VSixtyFiveYield", f"{y['v65']:.3f}")
    put("AFortyFiveYield", pct(y["a45"]))
    put("ASixtyFiveYield", pct(y["a65"]))
    safety_names = [n for n in by if n != "yield"]
    put("RHatMin", f"{100 * min(by[n]['rhat'] for n in safety_names):.1f}")
    put("RHatMax", f"{100 * max(by[n]['rhat'] for n in safety_names):.1f}")
    put("SeedGainTwo", f"{100 * (by['base_k2']['vmax'] / by['base']['vmax'] - 1):.1f}")
    put("SeedGainFive", f"{100 * (by['base_k5']['vmax'] / by['base']['vmax'] - 1):.1f}")
    put("RHatSeedTwo", f"{100 * by['base_k2']['rhat']:.1f}")
    put("RHatSeedFive", f"{100 * by['base_k5']['rhat']:.1f}")
    put("RHatAbarFive", f"{100 * by['abar5']['rhat']:.1f}")
    put("RHatAbarTwenty", f"{100 * by['abar20']['rhat']:.1f}")
    put("LoNinetyNine", f"{100 * b['lo99']:.1f}")
    put("HiNinetyNine", f"{100 * b['hi99']:.1f}")

    # Common holding period: lenders evaluate the expected average return over the same H years as
    # the safety criterion (and over 5 years), starting at launch with the seed as the reserve.
    pgrids = {10: grids, 5: {0.0: safety_grid(lm, 0.0, 5)}}
    ygrids = {10: {k: yield_grid(lm, k, 10) for k in (0.0, 0.02)}, 5: {0.0: yield_grid(lm, 0.0, 5)}}
    horizon_scenarios = [
        # name, eta, tau, abar, k, years
        ("h10_yield", 1.0, 0.01, None, 0.0, 10),
        ("h10", 1.0, 0.01, 0.10, 0.0, 10),
        ("h10_abar5", 1.0, 0.01, 0.05, 0.0, 10),
        ("h10_abar20", 1.0, 0.01, 0.20, 0.0, 10),
        ("h10_eta2", 2.0, 0.01, 0.10, 0.0, 10),
        ("h10_k2", 1.0, 0.01, 0.10, 0.02, 10),
        ("h5_yield", 1.0, 0.01, None, 0.0, 5),
        ("h5", 1.0, 0.01, 0.10, 0.0, 5),
    ]
    hsummary = {}
    hcurves = {}
    for name, eta, tau, abar, k, yrs in horizon_scenarios:
        mk = Market(pgrids[yrs][0.0], eta, tau, abar, ygrid0=ygrids[yrs][0.0])
        pts = [mk.solve(r, pgrids[yrs][k], ygrids[yrs][k]) for r in fine]
        a_s, v_s, s = summarise(pts, fine)
        hcurves[name] = (a_s, v_s)
        hsummary[name] = {"name": name, "eta": eta, "tau": tau, "abar": abar, "k": k, "years": yrs, **s}
    write_csv("equilibrium_horizon_curves.csv", [
        {"r": float(r), **{f"a_{n}": 100 * float(hcurves[n][0][i]) for n in hcurves},
         **{f"v_{n}": float(hcurves[n][1][i]) for n in hcurves}}
        for i, r in enumerate(fine)
    ])
    write_csv("equilibrium_horizon_summary.csv", list(hsummary.values()))
    lines = []
    for name in ("h10_yield", "h10", "h10_abar5", "h10_abar20", "h10_eta2", "h10_k2", "h5_yield", "h5"):
        s = hsummary[name]
        abar = "$\\infty$" if s["abar"] is None else f"{100 * s['abar']:.0f}"
        lines.append(
            f"{s['years']} & {s['eta']:g} & {abar} & {100 * s['k']:.0f} & {100 * s['rhat']:.1f} & {s['vmax']:.3f} & "
            f"{100 * s['lo99']:.1f}--{100 * s['hi99']:.1f} & {s['v0']:.3f} & {s['v45']:.3f} & {s['v55']:.3f} & {s['v65']:.3f} \\\\"
        )
    write_tex("table_equilibrium_horizon.tex", lines)
    h = hsummary["h10"]
    put("RHatHTen", f"{100 * h['rhat']:.1f}")
    put("VMaxHTen", f"{h['vmax']:.3f}")
    put("LoNinetyNineHTen", f"{100 * h['lo99']:.1f}")
    put("HiNinetyNineHTen", f"{100 * h['hi99']:.1f}")
    put("VZeroHTen", f"{h['v0']:.3f}")
    put("VFortyFiveHTen", f"{h['v45']:.3f}")
    put("VSixtyFiveHTen", f"{h['v65']:.3f}")
    put("AFortyFiveHTen", pct(h["a45"]))
    hy = hsummary["h10_yield"]
    put("RHatHTenYield", f"{100 * hy['rhat']:.1f}")
    put("VZeroHTenYield", f"{hy['v0']:.3f}")
    put("VFortyFiveHTenYield", f"{hy['v45']:.3f}")
    put("VSixtyFiveHTenYield", f"{hy['v65']:.3f}")
    put("RHatHFive", f"{100 * hsummary['h5']['rhat']:.1f}")
    put("LoNinetyNineHFive", f"{100 * hsummary['h5']['lo99']:.1f}")
    put("HiNinetyNineHFive", f"{100 * hsummary['h5']['hi99']:.1f}")
    put("RHatHTenKTwo", f"{100 * hsummary['h10_k2']['rhat']:.1f}")
    hnames = [n for n in hsummary if hsummary[n]["abar"] is not None]
    put("RHatHMin", f"{100 * min(hsummary[n]['rhat'] for n in hnames):.1f}")
    put("RHatHMax", f"{100 * max(hsummary[n]['rhat'] for n in hnames):.1f}")
    # The ten-year yield itself, at the production APR, by share (seed 0): what the build-up costs.
    put("YTenAtRC", pct(interp_p(ygrids[10][0.0], R_C, A_REF)))
    put("YTenAtZero", pct(interp_p(ygrids[10][0.0], 0.0, A_REF)))
    put("YTenAtFortyFive", pct(interp_p(ygrids[10][0.0], 0.45, A_REF)))
    put("YLongAtRC", pct(long_run_yield(A_REF, R_C)))

    # Sensitivity of the plateau (base scenario, long-run rule) to the simulated paths and to the
    # grid on which the safety surface is interpolated.
    grid_b = safety_grid(lm_safe[:, N_GRID:2 * N_GRID], 0.0)
    grid_f = safety_grid(lm, 0.0, H, R_GRID_FINE, A_GRID_FINE)
    sens = []
    lines = []
    for label, g, rg, ag in (("paths A, grid 1.25/0.5", grids[0.0], R_GRID, A_GRID),
                             ("paths B, grid 1.25/0.5", grid_b, R_GRID, A_GRID),
                             ("paths A, grid 0.625/0.25", grid_f, R_GRID_FINE, A_GRID_FINE)):
        mk = Market(g, 1.0, 0.01, 0.10, rg=rg, ag=ag)
        _, _, s = summarise([mk.solve(r, g) for r in fine], fine)
        sens.append(s)
        lines.append(f"{label} & {100 * s['rhat']:.1f} & {100 * s['lo99']:.1f}--{100 * s['hi99']:.1f} & "
                     f"{s['vmax']:.3f} & {s['v45']:.3f} & {s['v65']:.3f} \\\\")
    write_tex("table_plateau_sensitivity.tex", lines)
    put("RHatSpread", f"{100 * (max(s['rhat'] for s in sens) - min(s['rhat'] for s in sens)):.1f}")
    put("PlateauLoSpread", f"{100 * (max(s['lo99'] for s in sens) - min(s['lo99'] for s in sens)):.1f}")
    put("PlateauHiSpread", f"{100 * (max(s['hi99'] for s in sens) - min(s['hi99'] for s in sens)):.1f}")
    by["h10"] = h

    # Incidence check (yield-only): d ln a / d r = eps/(eta+eps) * 1/(1-f-r), eps = supply elasticity.
    mk = Market(grids[0.0], 1.0, 0.01, None)
    worst = 0.0
    lines = []
    for r in (0.45, 0.50, 0.55, 0.60):
        d = 1e-4
        a_hi, _ = mk.solve(r + d, grids[0.0])
        a_lo, _ = mk.solve(r - d, grids[0.0])
        a0, v0 = mk.solve(r, grids[0.0])
        num = (np.log(a_hi) - np.log(a_lo)) / (2 * d)
        c = long_run_yield(a0, r)
        x = c - E
        eps = c * (np.exp(-x / mk.tau) / mk.tau) / (1 - np.exp(-x / mk.tau))   # d ln G / d ln c
        eta = mk.eta
        formula = eps / (eta + eps) / (1 - F - r)
        worst = max(worst, abs(num - formula) / formula)
        lines.append(f"{100 * r:.0f} & {eps:.2f} & {100 * eps / (eta + eps):.1f} & {num:.3f} & {formula:.3f} \\\\")
        if abs(r - 0.50) < 1e-9:
            put("VolPerPointFifty", f"{100 * eta * eps / (eta + eps) / (1 - F - r) / 100:.1f}")
    write_tex("table_incidence.tex", lines)
    put("IncidenceErr", f"{100 * worst:.2f}")

    # Supply and demand curves for the figure (yield only): APR needed for lenders to fund volume V.
    rows = []
    for v in np.round(np.arange(0.55, 1.3001, 0.025), 3):
        rec = {"v": float(v), "demand": 100 * A_REF * v ** (-1.0 / mk.eta)}
        d_dep = v / U / mk.w_hat           # deposits as a share of the lenders' capacity
        if d_dep >= 1:                      # beyond the lenders' total capacity
            break
        psi = -mk.tau * np.log(1 - d_dep)                # marginal lender's required margin over e
        for r, tag in ((R_C, "rc"), (0.50, "r50"), (0.60, "r60")):
            a_free = ((E + psi) / U + EL) / (1 - F)
            a_lock = (E + psi) / (U * (1 - F - r))
            rec[f"s_{tag}"] = 100 * max(a_free, a_lock)
        rows.append(rec)
    write_csv("supply_demand.csv", rows)
    return by


# ------------------------------------------------------------------------------------------------
# E. Liquidity
# ------------------------------------------------------------------------------------------------
def wait_days(w, u, cushion):
    """Days until a run of a fraction w of deposits is paid out (Proposition 5)."""
    q0 = (1 - u) + cushion
    return TERM_DAYS * max(w - q0, 0.0) / u


def u_liquid(w_run, wait_target, cushion):
    """Largest utilisation for which a run of w_run is paid within wait_target days."""
    return TERM_DAYS * (1 - w_run + cushion) / (TERM_DAYS - wait_target)


def section_e():
    rows = []
    for w in np.round(np.arange(0.0, 1.0001, 0.025), 3):
        rows.append({"w": float(w), "u70": wait_days(w, 0.70, 0.0), "u85": wait_days(w, 0.85, 0.0),
                     "u90": wait_days(w, 0.90, 0.0), "u85c": wait_days(w, 0.85, 0.10)})
    write_csv("liquidity_curve.csv", rows)
    put("WaitFull", f"{wait_days(1.0, U, 0.0):.0f}")
    put("WaitFullCushion", f"{wait_days(1.0, U, 0.10):.0f}")
    put("WaitHalf", f"{wait_days(0.5, U, 0.0):.1f}")
    put("WaitQuarter", f"{wait_days(0.25, U, 0.0):.1f}")
    put("WaitThreeQuarter", f"{wait_days(0.75, U, 0.0):.1f}")
    put("WaitHalfCap", f"{wait_days(0.5, 0.90, 0.0):.1f}")
    put("TermDays", f"{TERM_DAYS:.0f}")
    lines = []
    for w_run in (0.25, 0.50, 0.75):
        cells = []
        for target in (3, 7, 14):
            u_max = min(0.90, u_liquid(w_run, target, 0.0))
            a0 = (E / u_max + EL) / (1 - F)
            cells.append(f"{100 * u_max:.0f} & {pct(a0)}")
        lines.append(f"{100 * w_run:.0f} & " + " & ".join(cells) + " \\\\")
    write_tex("table_liquidity.tex", lines)
    put("UMaxHalfWeek", f"{100 * min(0.90, u_liquid(0.5, 7, 0.0)):.0f}")
    put("UMaxHalfWeekCushion", f"{100 * min(0.90, u_liquid(0.5, 7, 0.10)):.0f}")
    put("AFreeAtULiq", pct((E / min(0.90, u_liquid(0.5, 7, 0.0)) + EL) / (1 - F)))
    put("AFreeAtCap", pct((E / 0.90 + EL) / (1 - F)))


# ------------------------------------------------------------------------------------------------
# F. Adverse selection threshold
# ------------------------------------------------------------------------------------------------
def section_f():
    d = 1e-4
    el_hi = float(vs.replenished_expected_loss(PD + d, vs.basel_other_retail_correlation(PD + d)))
    el_lo = float(vs.replenished_expected_loss(PD - d, vs.basel_other_retail_correlation(PD - d)))
    kappa = (el_hi - el_lo) / (2 * d)
    put("KappaLoss", f"{kappa:.2f}")
    put("GammaBackward", f"{(1 - F) / kappa:.2f}")       # lenders' yield bends back above this
    put("GammaProtectFortyFive", f"{0.45 / kappa:.2f}")  # the reserve keeps covering losses up to this
    put("GammaProtectSixtyFive", f"{0.65 / kappa:.2f}")


def write_key(by):
    b, y = by["base"], by["yield"]
    write_csv("key.csv", [{
        "pd": PD, "premium_bps": PREMIUM * 1e4, "apr": A_REF, "el": EL, "r_c": R_C,
        "a_free": ((E / U) + EL) / (1 - F), "r_max_lenders": 1 - F - E / (U * A_REF),
        "rhat_base": b["rhat"], "lo99": b["lo99"], "hi99": b["hi99"], "v45_base": b["v45"], "v55_base": b["v55"],
        "v65_base": b["v65"], "v45_yield": y["v45"], "v65_yield": y["v65"],
        "rhat_h10": by["h10"]["rhat"], "lo99_h10": by["h10"]["lo99"], "hi99_h10": by["h10"]["hi99"],
        "v45_h10": by["h10"]["v45"], "v65_h10": by["h10"]["v65"],
    }])


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    section_a()
    section_b()
    lm = section_c()
    by = section_d(lm)
    write_key(by)
    section_e()
    section_f()
    with open(OUT / "summary.tex", "w") as fh:
        fh.write(HEADER)
        for k, v in macros.items():
            fh.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
    print(f"wrote {len(macros)} macros; EL={EL:.4f} R_C={R_C:.4f} a_ref={A_REF:.4f}")


if __name__ == "__main__":
    main()
