#!/usr/bin/env python3
"""Table of key numbers for the three default-rate scenarios (data/key.csv and data/robust/*/key.csv).

Usage: python3 scripts/robustness_table.py     (after scripts/run_all.sh)
"""
import csv
import pathlib

DATA = pathlib.Path(__file__).resolve().parent.parent / "data"
HEADER = "% Generated by scripts/robustness_table.py; do not edit.\n"


def read(path):
    return {k: float(v) for k, v in next(csv.DictReader(open(path))).items()}


rows = [read(DATA / "robust/pd3/key.csv"), read(DATA / "key.csv"), read(DATA / "robust/pd10/key.csv")]
lines = []
for k in rows:
    lines.append(
        f"{100 * k['pd']:.0f} & {k['premium_bps']:.0f} & {100 * k['apr']:.2f} & {100 * k['el']:.2f} & "
        f"{100 * k['r_c']:.1f} & {100 * k['a_free']:.2f} & {100 * k['r_max_lenders']:.1f} & "
        f"{100 * k['rhat_base']:.1f} & {100 * k['lo99']:.1f}--{100 * k['hi99']:.1f} & "
        f"{k['v45_base']:.3f} & {k['v65_base']:.3f} \\\\"
    )
with open(DATA / "table_robust.tex", "w") as fh:
    fh.write(HEADER)
    fh.write("\n".join(lines) + "\n")
